### ISSUE TITLE
[REPORT] Draft report outline

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#10]
Why: we should all have a common and clear understanding of what is needed
What: prepare the outline of the future SOGS report

Scope:
- [x] Anita to prepare [the first draft](https://docs.google.com/document/d/1qjGonShs-2G0ia4xPLi55oBQubQnwfDSjgo52hWlcIs/edit?usp=sharing) (please request access if needed)
- [x] Review and discuss in WG call
- [x] Ismael to update the draft – [see new version here for review](https://docs.google.com/document/d/1ahV9DCoS16rIJXF1c4-6wYf9sNcIXUxrFEfibW4Q54c/edit)
- [ ] Ismael & Asim to make sure the report outline is aligned with the structure of the **survey** 
- [ ] Ismael & Asim to make sure **TOC** is incorporated (Asim & Ismael working on this)

**Comment by holanita** [comment]
Transferred to new SoGS repo. @Leamsi9 as discussed pls add your doc to this repo and comment here by Thu/Fri. Thanks.

**Comment by Leamsi9** [comment]
New draft outline is ready for review/approval
https://github.com/Green-Software-Foundation/state-of-green-software/discussions/18

**Comment by Leamsi9** [comment]
Google docs version: https://docs.google.com/document/d/1ahV9DCoS16rIJXF1c4-6wYf9sNcIXUxrFEfibW4Q54c/edit?usp=sharing

**Comment by holanita** [comment]
Discussed in the WG call today. Comments to be added.

**Comment by jawache** [comment]
@Leamsi9 will leave some comments in the doc but some overall big picture characteristics I think we need to settle on.

1. More I think about it the ToC from the GSF needs to show up in the report more. Our ToC is something we firmly believe in and was generated through consensus over 6 long workshop sessions so it's part of our DNA (which we need to manifest in everything we do). In case you've not had a chance to read it here is the link: https://www.figma.com/file/9xjePKRWrLU0fGyUwHpMEF/GSF-Diagram?node-id=21%3A759 (blog post immanent) 

Tech Culture, Knowledge and Tooling should be their own headings, our belief is that these are the core areas we need to focus on to get the impact we want. All your headings fit into these so I'm not saying cut anything, just highlight how these sections speak to our ToC.

2. Let's settle on a length and tone for the report. It should be short and digestible. I would suggest 20 or so pages, can skim in a minute and digest fully in 20. Or perhaps structured in 3 ways, exec summary, one pager summery for each section, section details. With target page lengths for each.

3. I'm a little unclear how the survey is incorporated in the report? I really like how the survey is structured in awareness, adoption, friction, enablers but I don't see how this shows up in he report. E.g. I would expect a heading called Awareness which contains some desktop research in this areas, interviews PLUS the survey results for awareness. Put it another way, the survey being structed one way and the report being structured another way doesn't quite make sense.

**Comment by jawache** [comment]
I had another thought today @Leamsi9 given we are web-first and we've discussed before how we need to think about the end product (#12) the current outline is linear, I think structuring this outline as a deck would be better.

- Will allow for more non-linear thinking, every slide can represent a page and that page needs to live standalone. I'm worried the linear nature of the outline will limit our options, let's think non-linearly from the get-go. 
- We can start thinking now about how best to layout each page for max digestibility, get Namrata involved and Osama will be able to start planning the website now since he'll have an outline that maps better to the web.
- We've got the questions, a deck format will allow us to think a little about how those questions show up in the final website and explain that to Osama so he can start working on designs for the final website now.
- I can use that deck to sell the SoGS to our members, I can present to orgs and convince them to send the survey out internally. This is going to be my primary activity post COP, I'm going to have to sell this thing and this will help me sell it.

Generally I think a deck is going to be a better tool for planning this outline and can then serve as a tool for explaining the end product to others. If we outline as a normal google doc, I'm pretty sure the end product is going to end up looking like a google doc but on the web,

**Comment by Leamsi9** [comment]
Could you elaborate on what you have in mind as a deck? Aren't decks also
sequential, i.e. linear? Would not each section in the outline translate
into a deck slide,  web page, except the latter allows for more formats
than a traditional deck, such as collapsible mind maps, live data
dashboards, hyperlinked docs, etc?

I feel I may be missing your vision here, but happy to follow it!

**Comment by elisezelechowski** [comment]
Could we jump on a call in the next few days to discuss or is it best to
wait until Monday's policy meeting?

**Comment by jawache** [comment]
I've come up with i "think" a rough idea about how to bring all of this together, esp. our TOC and Survey. Will share with @Leamsi9 tomorrow and see if it resolves some of the above.

**Comment by jawache** [comment]
@Leamsi9 how's the update to the outline going? I was hoping we could review before todays call but at the very least let's have something to review before the Policy WG call on Monday.

**Comment by holanita** [comment]
Discussed today:
- need to flash out at least one section to make the end product 100% clear (using lorem ipsum is fine)
- add a one-paragraph executive summary at the beginning of each section (opinionated summary / our added-value)
- add (links to ?) further resources to be added separately to back up the data
- use infographics for each sub-section (e.g. for awareness?) 
- etc.

**Comment by holanita** [comment]
Discussed in today's WG call and received positive feedback from Chris & Elise. Team to continue review async.

**Comment by holanita** [comment]
Not aware of any new comments via GH or the google form. @Leamsi9 please keep this ticket updated so we know what is going on with the report outline.

**Comment by holanita** [comment]
@Leamsi9 so today Asim mentioned that Osama could start working on the website in December as long as he has the headings. I assume it's the finalized draft outline that he needs (just the headings). Do you have a specific ETA for finalizing headings?

**Comment by Leamsi9** [comment]
Apologies, just been trying to focus on writing! Yes these are the headings. I did see the comment that Osama will need more on types of data. That might be one week away, as the Business Case is probably an outlier. But we should have enough to at least get started. As soon as I complete the first section I will return to this issue and have something for Osama.

**Comment by holanita** [comment]
Brilliant, thank you! I'm closing this task then, let's continue the convo [on this web ticket](https://github.com/Green-Software-Foundation/state-of-green-software/issues/35) in a week or so when you are ready.
