### ISSUE TITLE
Insight 6: Scaling green software requires regional research in many languages

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#100]
Parent issue https://github.com/Green-Software-Foundation/state-of-green-software/issues/101

**Insight lifecycle**

- [x] Draft is created (gdoc)
- [x] Reviewed by editor (gdoc)
- [x] Content reviewed by Marketing (gdoc)
- [x] Final approve by Tamara (gdoc)
- [x] Graphics created (gdoc -> assets)
- [x] Published (gdoc -> md)

**Comment by jawache** [comment]
@Oleg-Zhymolokhov it would be useful to put the gdoc links in these issues, hard to go back and forth otherwise.

**Comment by Oleg-Zhymolokhov** [comment]
@jawache @Jenya-design @tamigraph @cathmaughan @NAMRATA-WOKE I've added the link to the GDrive folder to the root issue.

**Comment by cathmaughan** [comment]
@Jenya-design  @NAMRATA-WOKE we need to be consistent with capitalisation of "green software". I think I missed this in Insight 3 as well. In both cases, they should be lower case and onl upper case when we're talking about the report.
I also think the title is a little confusing - research is not needed in different languages, but resources. So maybe "Scaling green software requires regional research and resources in multiple languages".
The text on the second page can be edited a bit as well. I think it's fine in the context of the insight, but here it could sound better "Green software research is currently concentrated in China, the global leader in green computing, followed by the USA, India, the UK and Australia."

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE @cathmaughan

Images for Insight 6 are updated
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Folder with the illustrations/elements [here](https://www.canva.com/folder/FAFfC6DLAiU)

![Image](https://user-images.githubusercontent.com/69306070/233651439-6425d629-acbd-43cb-a6ee-2f05d97cc015.png)

![Image](https://user-images.githubusercontent.com/69306070/233651438-e8612097-092d-4332-be40-07a13f939323.png)
