### ISSUE TITLE
Insight 9: Developers strive for eco-friendly software but lack resources

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#105]
Parent issue #101

**Insight lifecycle**

- [x] Draft is created (gdoc)
- [x] Reviewed by editor (gdoc)
- [x] Content reviewed by Marketing (gdoc)
- [x] Final approve by Tamara (gdoc)
- [x] Graphics created (gdoc -> assets)
- [x] Published (gdoc -> md)

**Comment by Jenya-design** [comment]
Hello @jawache @NAMRATA-WOKE @cathmaughan

Please review the update for the Insight 9 attached
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Folder with the illustrations/elements [here](https://www.canva.com/folder/FAFfC6DLAiU)


![Image](https://user-images.githubusercontent.com/69306070/232445547-7bf771ab-fc6c-43f7-86e2-cec9d20776c8.png)
