### ISSUE TITLE
Insight 11: Sustainability is part of employee recruitment and retention

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#107]
Parent issue #101

**Insight lifecycle**

- [x] Draft is created (gdoc)
- [x] Reviewed by editor (gdoc)
- [x] Content reviewed by Marketing (gdoc)
- [x] Final approve by Tamara (gdoc)
- [x] Graphics created (gdoc -> assets)
- [x] Published (gdoc -> md)

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE @cathmaughan

Please review new update for the Insight 11 attached
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Folder with the illustrations/elements [here](https://www.canva.com/folder/FAFfC6DLAiU)

![Image](https://user-images.githubusercontent.com/69306070/233652030-1f78dc16-d0d6-46c3-b4f6-86e3806f130e.png)

**Comment by cathmaughan** [comment]
I think we can make this more impactful with "Sustainability is a key factor in employee recruitment and retention" or "Sustainability is key for employee recruitment and retention"

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE @cathmaughan @jawache 

Please review the update for Insight 11 attached
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Folder with the illustrations/elements [here](https://www.canva.com/folder/FAFfC6DLAiU)

![12](https://user-images.githubusercontent.com/69306070/235148371-37506928-73bf-4ba0-9792-498e916fadfa.png)

**Comment by Oleg-Zhymolokhov** [comment]
@NAMRATA-WOKE Do you agree with Cath's proposition to change the title?

**Comment by NAMRATA-WOKE** [comment]
@Oleg-Zhymolokhov @Jenya-design @cathmaughan I am fine with this. If we want to pack more of a punch, we can say:

Sustainability is essential for employee recruitment and retention
