### ISSUE TITLE
[PM] SOGS Progress

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#11]
Why: this ticket is to help us track the progress of the project team (Ismael, Tamara, Zane + Asim, Anita)
What: Anita will be updating this ticket weekly / as needed / before each WG call

**Comment by holanita** [comment]
Meeting done. Progress looks great. Survey seems doable. Draft survey to be shared with the WG on Monday. 

Next steps as per [GANTT](https://view.monday.com/3205828327-c53ddd26e774008fc5a4c6a55a76058c?r=use1):
- on Oct 17: WG call to discuss draft survey and confirm survey tool
- by Oct 20: work async and adjust draft survey if needed
- on Oct 20: Team call to discuss updates and next steps if needed
- by Oct 27: Anita to set up survey tool (Survey Monkey) ?
- on Oct 27: Team call to review survey tool
- by Oct 31: work async and adjust survey tool if needed
- on Oct 31: WG call to discuss and close project
- by Nov 1: finalize everything

**Comment by holanita** [comment]
Progress report for the WG call today (Oct 31):
- WG to review and test [the Survey Monkey questionnaire](https://www.surveymonkey.com/r/Preview/?sm=0VKpgfUwJtdFhr1nqqhXmmGA6aKcxGyjyjYsY3LoeHVCE0kVd6hw08FPTbZbjm8_2F) 
- Ismael/Asim to explain report outline and share fleshed out section as per the discussion today
- Ismael to list suggested interviews, with a few questions for the PolicyWG for who to interview

**Comment by holanita** [comment]
As discuss in the WG call today:
- WG to review and test [the Survey Monkey questionnaire](https://www.surveymonkey.com/r/Preview/?sm=0VKpgfUwJtdFhr1nqqhXmmGA6aKcxGyjyjYsY3LoeHVCE0kVd6hw08FPTbZbjm8_2F) **by tomorrow**
- WG to review the [report outline](https://docs.google.com/document/d/1ahV9DCoS16rIJXF1c4-6wYf9sNcIXUxrFEfibW4Q54c/edit#heading=h.wzs1w3olflim) **async** 
- Anita to turn Ismael's [suggested interviews](https://docs.google.com/document/d/19Df29OzpvH09b8RETJlq6y82Zkv7Urt3GyNuTwxPjM4/edit) into a trackable spreadsheet **asap**

**Comment by holanita** [comment]
No feedback received on survey and report outline so far. Interviews added to spreadsheet.

**Comment by holanita** [comment]
Upcoming key deadlines in line with [Ismael's GANTT](https://docs.google.com/spreadsheets/d/1d0EUEQRaTgTu-aYRpHfs7J8MO1Fc9AI9RXeJN3WyNyE/edit#gid=1115838130) and our originally planned [milestones](https://docs.google.com/document/d/1dmKSWMJ5BIAPmkpiy_d3X1pHqC3sfTVd6TmkybrnSkE/edit#) 
(the two are no longer aligned, dates to be monitored and updated on an ongoing basis)
- [ ] Oct 31 plan and agree on 🔴 **interviews** (number, async vs sync)
- [ ] Oct 31 finalize 🔵 **desk research** for report outline
- [ ] Nov 4 last team call before COP – discuss 🟢 **SM survey** + these deadlines
- [ ] Nov 9 finalize 🔵 **desk research** for business case
- [ ] Nov 9 final test of 🟢 **SM survey** setup and design (Anita)
- [ ] Nov 14 WG start monitoring 🟢 **SM survey** and 🔴 **interviews**
- [ ] Nov 17 finalize 🔵 **desk research** for knowledge
- [ ] Nov 25 finalize 🔵 **desk research** for culture
- [ ] Nov 28 WG monitor 🟢 **SM survey** and 🔴 **interviews**
- [ ] Dec 5 finalize 🔵 **desk research** for tooling
- [ ] Dec 12 WG monitor 🟢 **SM survey** and 🔴 **interviews** + make sure calls for 2023 are confirmed
- [ ] Jan 31 Asim/Sean to help land Big Names for 🔴 **interviews**
- [ ] Jan 31 Ismael to schedule and run 🔴 **interviews**

**Comment by holanita** [comment]
@Leamsi9 oh sorry, let me do this differently as this ticket is for bi-weekly updates. I'm afraid the point will now be lost.
- let's move granular discussions to separate tickets as always. we'll always have a dedicated ticket for each task.
- @seanmcilroy29 sorry for dragging you into this. we'll reach out when the time comes. let's not start the convo here.
- @Leamsi9 I'd like to create a proper gantt like i did last time. yours is out of date and hard to update. we need a better tool.
- like we discussed last time, let's have the big convos in the calls. we can cover everything this evening. hope this is ok.

**Comment by holanita** [comment]
From now on, KPIs will be tracked [in this spreadsheet](https://docs.google.com/spreadsheets/d/1x_R9Z0qIn7WGvSA_tuW2QHiJIOBjlR0OhjzuLg6aFFk/edit#gid=0). See also [this GH ticket](https://github.com/Green-Software-Foundation/state-of-green-software/issues/26).
Only Asim and Anita attended the last team call and Ismael has been out of reach since last week, so some tasks listed above are pending. Steph has started working on scheduling the interviews and we are monitoring survey results.

**Comment by holanita** [comment]
The WG call has been cancelled today. Both the interviews and desk research are behind schedule. We are looking for alternative solutions / help to speed things up. We also need to increase are marketing efforts relating to the survey.

**Comment by tamigraph** [comment]
> The WG call has been cancelled today. Both the interviews and desk research are behind schedule. We are looking for alternative solutions / help to speed things up. We also need to increase are marketing efforts relating to the survey.

I might be able to help out with the desk research and interviews if it will help us stay relatively on track.

**Comment by holanita** [comment]
Thanks @tamigraph! Asim suggested he would take over the interviews with the SC. You had another idea earlier about some additional interviews that might be worth revisiting – see [here](https://github.com/Green-Software-Foundation/state-of-green-software/issues/27). Also, we'll have a chat with Ismael to figure out how we can help with the desk research. I'll let you know as soon as I know more.

**Comment by holanita** [comment]
We'll do weekly sprints from now on
- see: https://github.com/Green-Software-Foundation/state-of-green-software/issues/71
- see also the weekly marketing tickets: https://github.com/Green-Software-Foundation/state-of-green-software/issues/67
- and this week's discussions with Ismael: https://github.com/Green-Software-Foundation/state-of-green-software/issues/69

**Comment by holanita** [comment]
Great progress with the survey thanks to Avanade (paid options still TBD). No news from Ismael. 2 interviews booked.
- New sprint for Ismael: https://github.com/Green-Software-Foundation/state-of-green-software/issues/82
- Marketing todos: https://github.com/Green-Software-Foundation/state-of-green-software/issues/81
- Cameron started working on the stakeholder map - also to be discussed with the WG
- [KPIs](https://docs.google.com/spreadsheets/d/1x_R9Z0qIn7WGvSA_tuW2QHiJIOBjlR0OhjzuLg6aFFk/edit#gid=0)

**Comment by holanita** [comment]
I'm closing this. New issues have been created to track progress with marketing / research / interviews.
