### ISSUE TITLE
Insight 16: Green software standards are proliferating rapidly

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#112]
Parent issue #101

**Insight lifecycle**

- [x] Draft is created (gdoc)
- [x] Reviewed by editor (gdoc)
- [x] Content reviewed by Marketing (gdoc)
- [x] Final approve by Tamara (gdoc)
- [x] Graphics created (gdoc -> assets)
- [x] Published (gdoc -> md)

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE @cathmaughan

Please review the update for the Insight 16 attached
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Folder with the illustrations/elements [here](https://www.canva.com/folder/FAFfC6DLAiU)


![Image](https://user-images.githubusercontent.com/69306070/233652842-205ffb9f-d32d-4d83-9e98-7b7a2a3d846f.png)

**Comment by cathmaughan** [comment]
The title doesn't scan well to me. I'd prefer "The rapid proliferation of green software standards" or "Green software standards are proliferating rapidly"

**Comment by tamigraph** [comment]
I agree with Cath. Maybe the second option so it's a complete sentence?

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE @cathmaughan @jawache

Please review the update for Insight 16 attached
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Folder with the illustrations/elements [here](https://www.canva.com/folder/FAFfC6DLAiU)

![17](https://user-images.githubusercontent.com/69306070/235149674-6495d7ec-8330-45fa-87e7-d7a2c6f98aed.png)
