### ISSUE TITLE
Insight 19: Green software principles must be a part of the user experience

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#115]
Parent issue #101

**Insight lifecycle**

- [x] Draft is created (gdoc)
- [x] Reviewed by editor (gdoc)
- [x] Content reviewed by Marketing (gdoc)
- [x] Final approve by Tamara (gdoc)
- [x] Graphics created (gdoc -> assets)
- [x] Published (gdoc -> md)

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE @cathmaughan @jawache

Please review the image for Insight 19 attached
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Folder with the illustrations/elements [here](https://www.canva.com/folder/FAFfC6DLAiU)

![Image](https://user-images.githubusercontent.com/69306070/235150489-62341f6a-07f3-4e53-a809-21e75d85a687.png)

**Comment by Oleg-Zhymolokhov** [comment]
@cathmaughan @NAMRATA-WOKE @tamigraph The main thing here is that all the software is designed for end-users. I'd change the title to the one that describes how green software should help end users make certain decisions to make green software even more effective. Smth like: "End users can help make green software more effective if it is designed respectively".

**Comment by cathmaughan** [comment]
@Oleg-Zhymolokhov I think if we have to rewrite, it will be something like "End users can help make green software more effective if it is designed with them in mind". I don't like this though because it is too long. Let's stick with the original, I think it's fine

**Comment by NAMRATA-WOKE** [comment]
@Oleg-Zhymolokhov @cathmaughan I re-read the insight. Would this work: Green software principles must be a part of the user experience

**Comment by tamigraph** [comment]
Just chiming in to say that @NAMRATA-WOKE's formulation is a good one. My point was that we need to consider the user experience of green software to make sure it can be implemented effectively

**Comment by Oleg-Zhymolokhov** [comment]
Let's stick with @NAMRATA-WOKE variant
