### ISSUE TITLE
Insight 21: Green software is central to tech ethics

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#117]
Parent issue #101

**Insight lifecycle**

- [x] Draft is created (gdoc)
- [x] Reviewed by editor (gdoc)
- [x] Content reviewed by Marketing (gdoc)
- [x] Final approve by Tamara (gdoc)
- [x] Graphics created (gdoc -> assets)
- [x] Published (gdoc -> md)

**Comment by cathmaughan** [comment]
Let's add a verb to make this more consistent with the other titles "Green software is central to tech ethics"

**Comment by Oleg-Zhymolokhov** [comment]
@Jenya-design I've updated the title in Canva according to Cath's comment.
