### ISSUE TITLE
SOGS report Survey functionality

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#119]
Parent issue #101 

As discussed with @osamajandali previously and based on comments from @jawache, creating this issue to track progress on:

- [x] SOGS website Tags
- [x] SOGS website Search functionality
- [ ] Separate page with Survey data and data-graphs (probably generated with some library) (TBD with @osamajandali)

**Comment by Oleg-Zhymolokhov** [comment]
@jawache we need to decide if we want the insights to be searchable by the content or by title only.  Personally, I think it should be searchable by content. To implement that Osama will need some additional time. 
@osamajandali can you tell if the indexing will update while we fill up the website incrementally?

**Comment by Oleg-Zhymolokhov** [comment]
@osamajandali Let's search the insights by title only.

**Comment by zanete** [comment]
@Oleg-Zhymolokhov  and @jawache confirm that Search is still a feature that will NOT be implemented in the first launch as per PPP/OKR review on 25th April https://github.com/Green-Software-Foundation/gsf-admin/issues/221

**Comment by Oleg-Zhymolokhov** [comment]
@zanete @jawache @osamajandali I think we should either remove Search field at all, or search by title only.

**Comment by osamajandali** [comment]
@Oleg-Zhymolokhov I believe that it will be useless to search by title, I'd go for removing the search

**Comment by Oleg-Zhymolokhov** [comment]
@zanete 
1) We agreed with Asim that tags will be for visual representation only (no filtering functionality). 
2) I will create a single document with all the insights where everyone can do a final read-through. It will be 27 insights this week. Once we make sure everything is final, I will start publishing insights to the website (I'll do it myself because I want @osamajandali to focus on the Survey-data page).
3) We can arrange a demo at the end of the next week. Hopefully, Tamara will finish the "Business case..." article and I will have 27 insights published.

**Comment by zanete** [comment]
Capturing the Status on weekly web call:
- @Oleg-Zhymolokhov is adding the content
- @osamajandali focusing on Survey, there is lack of clarity about the kind of visualisations should be shown, it would be beneficial to have a conversation with @Oleg-Zhymolokhov / @tamigraph regarding this (unless it all becomes clear once @osamajandali has access to Survey monkey)

**Comment by zanete** [comment]
Capturing the Status on weekly web call:
- The survey functionality is now ready for review: https://sogs-report.netlify.app/survey/
- Moved all other tasks to https://github.com/Green-Software-Foundation/state-of-green-software/issues/138

**Comment by zanete** [comment]
Capturing the Status on weekly web call:
* @Oleg-Zhymolokhov we'll close this as the remaining work appears to be distributed across all new SOGS issues
