### ISSUE TITLE
[WEBSITE] Meeting to discuss outline of report format

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/state-of-green-software#12]
Meeting to discuss the State of Green Software report format

Meeting to include: Asim, Ismael, Osama

**Comment by holanita** [comment]
To be revisted later. I'm assuming we are putting this on hold for now and will focus on creating the landing page for COP.

**Comment by jawache** [comment]
@holanita is this the ticket where we will be discussing the end website? if so then yet let's put this on hold for now. 
(I read this ticket as just the meeting to discuss in general which we had a while back)

**Comment by holanita** [comment]
Yeah, this was created by Sean. I had another ticket open for this, but I removed it to avoid the duplicate. I was thinking we could keep this one. Okay, agreed, on hold for now.
