### ISSUE TITLE
Insight 23: The games industry leads the way in green software principles

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#120]
Parent issue #101

**Insight lifecycle**

- [x] Draft is created (gdoc)
- [x] Reviewed by editor (gdoc)
- [x] Content reviewed by Marketing (gdoc)
- [x] Final approve by Tamara (gdoc)
- [x] Graphics created (gdoc -> assets)
- [x] Published (gdoc -> md)

**Comment by cathmaughan** [comment]
I think the title is fine but maybe a bit generic. How about "The games industry leads the way in green software principles"

**Comment by Jenya-design** [comment]
@Oleg-Zhymolokhov @NAMRATA-WOKE @cathmaughan 

Please review the update for Insight 23 attached 
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Folder with the illustrations/elements [here](https://www.canva.com/folder/FAFfC6DLAiU)


![Image](https://github.com/Green-Software-Foundation/state-of-green-software/assets/69306070/21df6e01-ebba-4f26-9509-c364ba3d52e4)
