### ISSUE TITLE
Insight 25: The application of green software principles is increasing rapidly

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#122]
Parent issue #101

**Insight lifecycle**

- [x] Draft is created (gdoc)
- [x] Reviewed by editor (gdoc)
- [x] Content reviewed by Marketing (gdoc)
- [x] Final approve by Tamara (gdoc)
- [x] Graphics created (gdoc -> assets)
- [x] Published (gdoc -> md)

**Comment by Jenya-design** [comment]
@Oleg-Zhymolokhov @NAMRATA-WOKE @cathmaughan

Please review the update for Insight 25 attached
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Folder with the illustrations/elements [here](https://www.canva.com/folder/FAFfC6DLAiU)


![Image](https://github.com/Green-Software-Foundation/state-of-green-software/assets/69306070/f94dab74-3f49-4cd4-b2c8-85aabc3051bb)

**Comment by cathmaughan** [comment]
On re-reading this, it doesn't quite work (the 'application is proliferating'). How about "The application of green software principles is increasingly" or "...increasing rapidly" for more emphasis?

**Comment by Jenya-design** [comment]
@cathmaughan @Oleg-Zhymolokhov 
Text is updated [in canva](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton), preview attached here

![Image](https://github.com/Green-Software-Foundation/state-of-green-software/assets/69306070/2a53a168-c1e1-415b-9461-5f518ce761f3)
