### ISSUE TITLE
Insight 26: There are 2,000 specialized green software tools available in open-source, commercial, and academic contexts

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#123]
Parent issue #101

**Insight lifecycle**

- [x] Draft is created (gdoc)
- [x] Reviewed by editor (gdoc)
- [x] Content reviewed by Marketing (gdoc)
- [x] Final approve by Tamara (gdoc)
- [x] Graphics created (gdoc -> assets)
- [x] Published (gdoc -> md)

**Comment by Jenya-design** [comment]
@Oleg-Zhymolokhov @NAMRATA-WOKE @cathmaughan

Please review the update for Insight 26 attached (2 images)
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Folder with the illustrations/elements [here](https://www.canva.com/folder/FAFfC6DLAiU)

![Image](https://github.com/Green-Software-Foundation/state-of-green-software/assets/69306070/6a2a3e68-9e42-4063-9db7-890dad4804d4)

![Image](https://github.com/Green-Software-Foundation/state-of-green-software/assets/69306070/9cc50bcb-d985-43e0-a681-721177d0fcaf)
