### ISSUE TITLE
Article "Business case for green software"

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#126]
Parent issue #101 

Keep it as a website page.

Text link: https://docs.google.com/document/d/1onS33Mx9dmKvJ1zLsQWnHO4BplN5NjjvkUeVwNcebg8/edit

**Comment by jawache** [comment]
Report: https://docs.google.com/document/d/1onS33Mx9dmKvJ1zLsQWnHO4BplN5NjjvkUeVwNcebg8/edit

**Comment by jawache** [comment]
I reviewed, it looks good to me, thanks @tamigraph !

**Comment by Oleg-Zhymolokhov** [comment]
@NAMRATA-WOKE review the  https://docs.google.com/document/d/1onS33Mx9dmKvJ1zLsQWnHO4BplN5NjjvkUeVwNcebg8/edit from your perspective

**Comment by Oleg-Zhymolokhov** [comment]
@osamajandali please add the document as a page as we agreed and I will update the file afterwards to create links to insights.
