### ISSUE TITLE
Write the title for the SOGS report website

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#127]
The website can be found here: https://heartfelt-babka-3b6ea9.netlify.app/

We need to have a text covering the "Title goes here" part.

**Comment by Oleg-Zhymolokhov** [comment]
@NAMRATA-WOKE I think you're the right person to write this one.

**Comment by NAMRATA-WOKE** [comment]
@Oleg-Zhymolokhov after working through a few permutations, my recommendation for the website is as follows:

Do not use the comlpete logo at the top. Only use the icon. The title itself should be:

**2023 State of Green Software**

The language below can be: 

_A new report that brings global insights and data from industry leaders and researchers to the forefront to reduce software's harm to Earth and increase investment in decarbonizing software at scale._
