### ISSUE TITLE
SOGS website complete rollout

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#129]
[Link](https://docs.google.com/document/d/147_VN3fAmIjlptURewQ6T4qMv8VJHRZc_UhoaHFy55A/edit?pli=1#heading=h.lac8aa7xqjgg) to the document with all insights.

Issue with detailed insights structure: #101 

Website link: https://sogs-report.netlify.app/

- [x] #127 
- [x] #138
- [x] #102
- [x] #159
- [x] #141
- [x] #125 
- [x] #147
- [x] #152
- [x] #150
- [x] #158
- [x] #174
- [x] #151
- [x] #163
- [x] #162
- [x] #161
- [x] #139 
- [x] #154
- [x] #173 
- [x] #153 
- [x] #149
- [x] #126 
- [x] #140 
- [x] #155
- [x] #148

**Comment by Oleg-Zhymolokhov** [comment]
The "Insights" text - change or remove?
Tags - make 10% smaller
Add header picture. 
Insights should have an outline

Fix the design according to [figma](https://www.figma.com/proto/B25vyo3My1SzrksFUe2B4p/GSF-Landing-Pages?page-id=901%3A358&node-id=1008-358&viewport=278%2C33%2C0.12&scaling=min-zoom&starting-point-node-id=1008%3A358&show-proto-sidebar=1)

**Comment by Jenya-design** [comment]
@Oleg-Zhymolokhov @cathmaughan @NAMRATA-WOKE 

Illustrations for Insights 1-30 are ready for your review 
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Folder with Canva elements [here](https://www.canva.com/folder/FAFfC6DLAiU)

[GSF Drive folder](https://drive.google.com/drive/folders/1-nBd1wmD1P9T6cfjBu4JD9P0GDPVxLlm?usp=share_link) with all png and ai source files

@osamajandali in case you need vector files, please check [this file](https://drive.google.com/file/d/1oF47RMY-u8m2Rem9ABnjQ4OOiYqKaPIF/view?usp=share_link)

Thank you

**Comment by zanete** [comment]
@Oleg-Zhymolokhov FYI I've moved all @osamajandali tasks to https://github.com/Green-Software-Foundation/state-of-green-software/issues/138, I hope that's ok, will be easier to manage and see what's left
