### ISSUE TITLE
[Survey] Create first set of questions 

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#13]
Questions & answers to be added and discussed [in this google doc](https://docs.google.com/document/d/1wNp2vBkwuvMnvcdyXR3VH9Pt8XaixrvPTaUGgfnGgew/edit?usp=sharing).

Next steps as of Oct 12:
- [x] converge to 20 questions by Thursday
- [x] discuss Q&A in team call on Thursday
- [x] update draft Q&A by the next WG call on Oct 17

**Comment by holanita** [comment]
The [draft survey](https://docs.google.com/document/d/1wNp2vBkwuvMnvcdyXR3VH9Pt8XaixrvPTaUGgfnGgew/edit#) is open for comments until Wednesday, October 19. As discussed in the WG call today, given the tight deadlines we will not be able to process major updates @mrchrisadams @elisezelechowski.

**Comment by jawache** [comment]
We reviewed this on the call today, we are happy with the questions and answers it's good to upload @holanita

**Comment by jawache** [comment]
@holanita @Leamsi9 suggested we explore https://yougov.co.uk/ since you can pay $1 per answer and they will source the people.

**Comment by holanita** [comment]
@jawache @Leamsi9 note and added the update to the [GH issue that covers the survey tool](https://github.com/Green-Software-Foundation/state-of-green-software/issues/14). 
As for this current issue, can we consider the survey content ([Q&A in this doc](https://docs.google.com/document/d/1wNp2vBkwuvMnvcdyXR3VH9Pt8XaixrvPTaUGgfnGgew/edit#heading=h.pfaozpy06c4o)) finalized or do you still expect changes?

**Comment by holanita** [comment]
Survey Monkey setup completed. Remaining topics to be discussed/confirmed:
- removed 2 questions in line with updates [in the file](https://docs.google.com/document/d/1wNp2vBkwuvMnvcdyXR3VH9Pt8XaixrvPTaUGgfnGgew/edit#). are further edits expected?
- which questions should be required: all except the last three?
- which questions should be multiple choice: Q13, Q18, Q19, Q21 only?
- add 'prefer not to answer' to questions 4?
- skip Q16 if Q15 is no...?
- added a scale to Q22
- added text field to specify contact details in Q25

**Comment by holanita** [comment]
We tested the survey and agreed on a few more updates in today's team call.

'Where and how do we add the definition of green software' remains TBD, we can even add images to the description!
- Add new question (Q2): What types of applications do you primarily build?  Cloud; Mobile; Desktop; IoT; Networking; Web; Machine Learning; Other
- Add N/A to Q12 (what if respondent is not a developer)
- Reword Q13 Which of the following green software principles do you incorporate in your development projects?
- Reword Q14 Which of the following green software principles do you want to incorporate into your development projects in the future?
- Answer options for Q13 and Q14: I create software that is carbon-efficient; I create software that is energy-efficient; I create carbon-aware software (e.g. I shift workloads to times and locations with clean energy supply); I create software that can run on older devices/hardware; I maximise the utilisation of my hardware; I minimise the amount of data my software sends/receives; I optimise my code by measuring its energy consumption / carbon footprint
- Turn Q18 and Q19 into a ranking question!!! 
- Add revenue as an answer option for Q19
- Change scaling for Q22 (1 should represent the most important option)

**Comment by holanita** [comment]
No feedback received from the WG. Sent an email to the project team to make sure each recent update is fine. Placeholder with definition of green software remains to be discussed. Next team call scheduled for Friday, Nov 4.

**Comment by holanita** [comment]
As discussed in today's call with Tamara and Ismael, the survey looks good to go. As for the description of green software, we should use what we have in the copy for the website. See below. I need to figure out how to add this in SM. Ideas discussed:
- [ ] Add an intro page at the beginning and put the copy there
- [ ] Add it to all the pages (top / bottom)

_What is green software?

Green software aims to reduce the carbon emissions associated with software. As such, green software is software that emits the least amount of carbon possible. This can be achieved by making software more energy efficient, using less hardware, or letting software do more when the electricity is clean and less when it's dirty._

**Comment by holanita** [comment]
Done. A tooltip has been added to each relevant question and the definition can be found at the bottom of each page. See [here](https://drive.google.com/file/d/1YInmcoD5ZYNFFvXHGlyhsKdgSqLGEuNu/view?usp=share_link).
