### ISSUE TITLE
Insight 28: Green software must account for global carbon intensity

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#133]
Parent issue #101

**Insight lifecycle**

- [x] Draft is created (gdoc)
- [x] Reviewed by editor (gdoc)
- [x] Content reviewed by Marketing (gdoc)
- [x] Final approve by Tamara (gdoc)
- [x] Graphics created (gdoc -> assets)
- [x] Published (gdoc -> md)

**Comment by Jenya-design** [comment]
@Oleg-Zhymolokhov 

Please check the update for the Insight 28 attached
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Folder with the illustrations/elements [here](https://www.canva.com/folder/FAFfC6DLAiU)


![Image](https://github.com/Green-Software-Foundation/state-of-green-software/assets/69306070/97ab1a40-e071-4576-9184-732ab85d4f51)

**Comment by Oleg-Zhymolokhov** [comment]
Updated the graphic according to comments in the main doc. Canva is updated too.

![28](https://github.com/Green-Software-Foundation/state-of-green-software/assets/125550685/23caaa1a-1817-43ad-a133-c86199ccc5a2)
