### ISSUE TITLE
Insight 29: Web3 rings alarm for green software practitioners

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#134]
Parent issue #101

**Insight lifecycle**

- [x] Draft is created (gdoc)
- [x] Reviewed by editor (gdoc)
- [x] Content reviewed by Marketing (gdoc)
- [x] Final approve by Tamara (gdoc)
- [x] Graphics created (gdoc -> assets)
- [x] Published (gdoc -> md)

**Comment by Jenya-design** [comment]
@Oleg-Zhymolokhov 

Please check new update for the Insight 29 attached
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Folder with the illustrations/elements [here](https://www.canva.com/folder/FAFfC6DLAiU)

![Image](https://github.com/Green-Software-Foundation/state-of-green-software/assets/69306070/756d16f3-1696-4058-8600-a5e8fd3349e9)

**Comment by Oleg-Zhymolokhov** [comment]
Graphics updated according to comments in the main doc:

![33](https://github.com/Green-Software-Foundation/state-of-green-software/assets/125550685/8ff6b0c1-7c19-41e6-9c30-42d795cda0ee)
