### ISSUE TITLE
Insight 30: Decarbonization alone cannot make software green

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#135]
Parent issue #101

**Insight lifecycle**

- [x] Draft is created (gdoc)
- [x] Reviewed by editor (gdoc)
- [x] Content reviewed by Marketing (gdoc)
- [x] Final approve by Tamara (gdoc)
- [x] Graphics created (gdoc -> assets)
- [x] Published (gdoc -> md)

**Comment by Jenya-design** [comment]
@Oleg-Zhymolokhov 

Please check new update for the Insight 30 attached
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Folder with the illustrations/elements [here](https://www.canva.com/folder/FAFfC6DLAiU)


![Image](https://github.com/Green-Software-Foundation/state-of-green-software/assets/69306070/c07751dc-cba0-499b-ae85-9027c28e10af)

**Comment by Oleg-Zhymolokhov** [comment]
Updated graphics according to comments in the main doc:

![30-decarbonization-alone-cannot-make-software-green](https://github.com/Green-Software-Foundation/state-of-green-software/assets/125550685/5809b25b-eff2-4e04-b44c-187de4595d5a)
