### ISSUE TITLE
Update GSF Website top banner with link to SOGS (31st of May launch)

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/state-of-green-software#139]
**Why**: SOGS report is a big deal and should be featured on the GSF website prominently
**What**: Updated website top banner that takes to SOGS report
**Scope of work**:
- [x] @NAMRATA-WOKE please provide a Call to Action for button and the tagline (Currently says "Learn how to build, maintain and run greener applications" with CTA "Take the course"
- [ ] @osamajandali to **activate** once SOGS website is live and all insights published

FYI @Oleg-Zhymolokhov

**Comment by NAMRATA-WOKE** [comment]
CTA: 

Green Software Foundation releases first-ever State of Green Software report.

**Comment by NAMRATA-WOKE** [comment]
Replace Learn how to build, maintain, and run greener applications with **Green Software Foundation releases first-ever State of Green Software report**

Button: View Insights

@osamajandali
