### ISSUE TITLE
Methodology page text

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#140]
Parent issue #129 

Methodology page will also have contributors list included (@tamigraph )

@namrata proposed to add "How to cite..."

**Comment by tamigraph** [comment]
> Parent issue #129
> 
> Methodology page will also have contributors list included (@tamigraph )

Methodology page including contributors list (acknowledgements) is complete. [https://docs.google.com/document/d/1IwlBSwlSjdoJUPqT__H-471Fvt5PotWIuKIJ9mdLR40/edit](url)

**Comment by zanete** [comment]
Capturing status of weekly call:
- @Oleg-Zhymolokhov can you confirm that there will be ab article created with the contents and published as a GSF article, and the link will be pointing to the GSF Article section? OR should Osama be building a special page?
- cc @jawache

**Comment by Oleg-Zhymolokhov** [comment]
@zanete As I understood, this will be an additional page on SOGS website, @jawache correct?

**Comment by osamajandali** [comment]
Updated!
