### ISSUE TITLE
Set up pop-up on GSf Website

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/state-of-green-software#143]
On May 32st, every user who visits the GSF website should see a pop-up page announcing the release of the SOGS website with a CTA: View the State of Green Software. 

Popup to include:

Headline: 

The First-Ever State of Green Software Report is Here! 

Text: 

A new report that brings global insights and data to the forefront to decarbonize software at scale.

The Green Software Foundation unveils 30 insights into trends, challenges, and opportunities to increase investment in green software and the wide-scale adoption of tools and principles to reduce software’s harmful effects on the environment. 

This is your access to the most relevant research, tools, practices and proof points to get your green software project funded and started.

CTA:

View the State of Green Software

**Comment by zanete** [comment]
@Oleg-Zhymolokhov can you clarify if this should be assigned to @osamajandali  and on his board? 
And if so, how high of a  priority does this task have given all else?

**Comment by Oleg-Zhymolokhov** [comment]
@zanete Closing as we agreed there will be functionality #139 implemented instead.
