### ISSUE TITLE
Re-visit insight tags

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#147]
Tags for each insight need to be updated.

**Comment by tamigraph** [comment]
I added the tags and preview text for all 30 insights to the SOGS rollout spreadsheet

**Comment by Oleg-Zhymolokhov** [comment]
@osamajandali it looks like tags do not work correctly if there are less than 3 of them.
Please take a look at this deployment https://deploy-preview-160--sogs-report.netlify.app/. Haven't merged it because we'll have a demo today.

**Comment by osamajandali** [comment]
Tags should be working now
