### ISSUE TITLE
[PM] Make this project visible to public

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#15]
@seanmcilroy29 not sure if you guys talked about this since last time. do you think it makes a difference if we keep all the projects private or should we publish them all?

**Comment by seanmcilroy29** [comment]
@holanita - We should try to keep all project public, unless it's specifically requested by the project members.

**Comment by holanita** [comment]
@seanmcilroy29 ok I see. I was just asking because as far as I can tell all of them are still private including the SoGS one. not sure if I'm looking at the right thing though... I clicked on [projects](https://github.com/orgs/Green-Software-Foundation/projects) and it says 'private' next to the project titles...

**Comment by holanita** [comment]
thanks
