### ISSUE TITLE
Change website buttons on the Insight page view

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#150]
Insights -> "More Insights"; Make it the only green button
Survey -> "Survey Data"; Remove it from Insight view (add this to a navbar)

![image](https://github.com/Green-Software-Foundation/state-of-green-software/assets/125550685/0c5562fe-ba12-47d9-8ae5-52944ac1d0cf)

**Comment by osamajandali** [comment]
Done!
