### ISSUE TITLE
Link to exported survey monkey data

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#151]
Parent issue: #129 

At the bottom of the survey graphs, we need a link pointing to the SOGS repo with a folder with csv files.

**Comment by osamajandali** [comment]
I made it a downloadable zip file where people can download all the data at once.

**Comment by Oleg-Zhymolokhov** [comment]
@osamajandali is it working now? I tried in both Chrome/EDGE and it says "No file"

<img width="247" alt="image" src="https://github.com/Green-Software-Foundation/state-of-green-software/assets/125550685/c50c83ca-51c4-4a80-9872-d1e1ec2868b5">

**Comment by osamajandali** [comment]
Fixed!
