### ISSUE TITLE
Theory of change link

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#152]
1) The content under 
https://greensoftware.foundation/articles/theory-of-change-defining-strategy-gsf 
should be appearing under 
https://greensoftware.foundation/articles/theory-of-change

2) Theory of Change button should lead to https://greensoftware.foundation/articles/theory-of-change 

3) Current content under https://greensoftware.foundation/articles/theory-of-change should be archived somehow (is it possible)?

**Comment by zanete** [comment]
Capturing the status during the weekly call:
- @Oleg-Zhymolokhov Slight confusion about scope here, Is @osamajandali expected to update the articles? He will do it but it wasn't clear

**Comment by Oleg-Zhymolokhov** [comment]
@zanete that was confusing indeed. I updated the issue information now. Should be clear what to do now.

**Comment by zanete** [comment]
@Oleg-Zhymolokhov @Stephaniestocker has done this lots in the past, but now @NAMRATA-WOKE and @ursvill also have the priviledges to do it. hope that helps?

**Comment by osamajandali** [comment]
Done!
