### ISSUE TITLE
Methodology page

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#153]
Parent issue: #129 

- [x] Create a Methodology link on the navbar (@osamajandali )
- [x] Create a new page with the text from here  [Link to the Methodology text](https://docs.google.com/document/d/1IwlBSwlSjdoJUPqT__H-471Fvt5PotWIuKIJ9mdLR40/edit)
- [x] Add the link to survey data in the Methodology page 
- [x] How to cite...?

**Comment by zanete** [comment]
@Oleg-Zhymolokhov can you confirm this should also be on @osamajandali board given he's one of the assignees?
And if there is any relation to https://github.com/Green-Software-Foundation/state-of-green-software/issues/140 ? is the tickbox in this issue replicated fully in issue #140 ?

**Comment by NAMRATA-WOKE** [comment]
Made my edits. Waiting to know the website link to plug in the citation text at the end of acknowledgements. I also made a comment for @jawache to see if we should include others under the Evangelists section of the acknowledgements. I feel like we should, but I am not 100% clear on who those people should be. @Oleg-Zhymolokhov you might need to follow-up with him!

**Comment by osamajandali** [comment]
Page added.
@Oleg-Zhymolokhov you can find the markdown file for the page [here](https://github.com/Green-Software-Foundation/state-of-green-software/blob/reports/src/pages/methodology.md) so you can edit/ update if needed
