### ISSUE TITLE
Change design of the buttons and change it navbar on the SOGS website

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#154]
Change current SOGS website buttons desing into a navbar as we agreed on the call.
There should be 5  links of the same importance. 
Three links instead of the buttons we currently have + Methodology page link + Survey Data link

**Comment by zanete** [comment]
@Oleg-Zhymolokhov can you confirm this issue would be on @osamajandali board? Is your expectation that he can begin work on this? I so, please can you provide the navbar links and a short description of the scope of this issue to avoid misunderstandings

**Comment by zanete** [comment]
also, @Oleg-Zhymolokhov , what is the relation to https://github.com/Green-Software-Foundation/state-of-green-software/issues/152 ? the navbar links are all part of issue #152, so this one is purely about the design?

**Comment by Oleg-Zhymolokhov** [comment]
@zanete @osamajandali Updated the issue,  added projects. Regarding the task: we had a conversation earlier this week and Osama knows what should be done there.

**Comment by Oleg-Zhymolokhov** [comment]
@zanete As mentioned in another issue - business case will be a separate page on the website. Osama has all the necessary data for it.

**Comment by osamajandali** [comment]
Done! I tweaked the layout a bit as well

**Comment by Oleg-Zhymolokhov** [comment]
Hey @osamajandali I think you might've missed a link to the Business case page. Has the page been added?

**Comment by osamajandali** [comment]
I missed this one sorry because it was not on the web board.
it's been added now
