### ISSUE TITLE
SEO for insight pages

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#158]
Parent issue #129 

The link to the text is [here](https://docs.google.com/spreadsheets/d/1iVJe3cEZ-KXP4jtbAewnAauoQaNZ2iTrbb1-SPM5Jas/edit#gid=0)

**Comment by Oleg-Zhymolokhov** [comment]
@osamajandali Tamara prepared the text. It's under the "Short description" column [here](https://docs.google.com/spreadsheets/d/1iVJe3cEZ-KXP4jtbAewnAauoQaNZ2iTrbb1-SPM5Jas/edit#gid=0)

**Comment by osamajandali** [comment]
Done!

**Comment by osamajandali** [comment]
@Oleg-Zhymolokhov This is actually from google when the title exceeded a certain length.
<img width="718" alt="image" src="https://github.com/Green-Software-Foundation/state-of-green-software/assets/13832392/b17f8de0-7ef3-4c96-a537-bc9394307001">

**Comment by Oleg-Zhymolokhov** [comment]
@osamajandali ok, then I think, I can close the issue
