### ISSUE TITLE
Change url names (filenames) for each insight

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#159]
Parent issue https://github.com/Green-Software-Foundation/state-of-green-software/issues/129

The link to the url names is [here](https://docs.google.com/spreadsheets/d/1iVJe3cEZ-KXP4jtbAewnAauoQaNZ2iTrbb1-SPM5Jas/edit#gid=0)

@Oleg-Zhymolokhov to come up with the initial names

@NAMRATA-WOKE to review

**Comment by NAMRATA-WOKE** [comment]
Done. Made some edits mostly to the URLs. Ended all descriptions with a period.
