### ISSUE TITLE
LinkedIn sharing fixed

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#162]
Parent issue: #129 

1) Take the text from https://github.com/Green-Software-Foundation/state-of-green-software/issues/149
2) Image should be Insight specific
3) The link should be pointing to the Insight

Sharing an insight to LinkedIn from the website doesn't work at the moment.

**Comment by osamajandali** [comment]
Hey @Oleg-Zhymolokhov, I found out that LinkedIn share url you can either share a link or text, but not both at the same time. Therefore, the share button will only allow us to share the link.

**Comment by osamajandali** [comment]
Done. Keep in mind that I am using the live url which is https://stateof.greensoftware.foundation/. So it will give `Something went wrong` error until we are live
