### ISSUE TITLE
Create a link at the footer to report bugs on the SOGS repo

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#163]
Parent issue: #129

Probably the link at the footer is the best way to do this.

Should point to: https://github.com/Green-Software-Foundation/state-of-green-software/issues/new?assignees=Oleg-Zhymolokhov&labels=bug&projects=&template=bug-report.md&title=

**Comment by osamajandali** [comment]
Added!
