### ISSUE TITLE
Analytics tracking implemented for social media sharing

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#166]
Parent issue: #129 

Track Insight sharing when Twitter and LinkedIn are being clicked on the website.

**Comment by osamajandali** [comment]
Hello @zanete, I am having trouble creating a new container for the SoGS website on our existing Google Tag Manager account. Is there any way I could be granted additional access to the account? Thank you.


![Image](https://github.com/Green-Software-Foundation/state-of-green-software/assets/13832392/5b024f6b-1fe1-42be-9b0c-bea5a852fc7f)

**Comment by zanete** [comment]
@osamajandali I've made you an admin, please check if you have rights now! Thanks

**Comment by osamajandali** [comment]
@zanete yes I have access now, thank you!

**Comment by osamajandali** [comment]
Done 
You can find it under events > link_id
- `twitter-share` for twitter
- `linkedin-share` for linkedin


![Image](https://github.com/Green-Software-Foundation/state-of-green-software/assets/13832392/ea4a067c-ba8d-44c9-98be-0111a9b36254)

**Comment by zanete** [comment]
@osamajandali which report in GA do you go to see this stat? I can't find a link_id event here: https://analytics.google.com/analytics/web/?pli=1#/p341502103/reports/explorer?params=_u..nav%3Dmaui%26_r.explorerCard..selmet%3D%5B%22eventCount%22%5D%26_r.explorerCard..seldim%3D%5B%22eventName%22%5D%26_u.comparisonOption%3Ddisabled%26_u.date00%3D20230531%26_u.date01%3D20230605&r=top-events&ruid=top-events,life-cycle,engagement&collectionId=life-cycle

**Comment by osamajandali** [comment]
@zanete, @jawache decided that we are not gonna launch with GTM as it created some tracking error and we will do it later on. So currently the links are not trackable

**Comment by zanete** [comment]
Capturing the status on weekly call:
- involving external consultant to find out why GA didn't work with tag manager

**Comment by zanete** [comment]
CApturing the status on weekly call:
- more testing required this week to see if its ok

**Comment by osamajandali** [comment]
It's working now from GTM and GA is working perfectly and it's tracking now twitter and linkedin clicks
@jawache @zanete @NAMRATA-WOKE
