### ISSUE TITLE
SOGS Social Media Toolkit

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/state-of-green-software#172]
What: A [document](https://docs.google.com/document/d/1S7DB5_d_6qf0Bj5wzCmhhDyUXHNdaP6H9iIWaptXhis/edit?usp=sharing) for GSF Members that provides pre-drafted content to share across their social media (LinkedIn and Twitter).
Why: Support members efforts to amplify the report and individual insights

**Comment by NAMRATA-WOKE** [comment]
@Oleg-Zhymolokhov can you share the link to report bugs on the site with me please?

**Comment by Oleg-Zhymolokhov** [comment]
@NAMRATA-WOKE here it is: https://github.com/Green-Software-Foundation/state-of-green-software/issues/new?assignees=Oleg-Zhymolokhov&labels=bug&projects=&template=bug-report.md&title=
