### ISSUE TITLE
Fix the "Sign up for the newsletter" submit button

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#173]
Parent issue: #129 

Why: Currently the button text is as on the screenshot:

<img width="917" alt="image" src="https://github.com/Green-Software-Foundation/state-of-green-software/assets/125550685/cb93b6bf-c732-42a5-b8f7-9431041147e1">

What: Change the button text to "Sign up"

**Comment by osamajandali** [comment]
Fixed !
