### ISSUE TITLE
Fix the color of the navbar on web view

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#174]
Parent issue: #129 

Why: There's a difference in background color for the main website and the navbar (I altered the contrast and brightness to make in more visible):

![telegram-cloud-document-2-5451794205779177207](https://github.com/Green-Software-Foundation/state-of-green-software/assets/125550685/93a800a8-a811-4358-aa35-787a88538084)

What: Fix the background color of navbar to match the rest of the website

**Comment by osamajandali** [comment]
Fixed
