### ISSUE TITLE
Link to the survey questions/page from other pages

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/state-of-green-software#181]
**Describe the bug**

In many places we talk about the "SOGS Survey" but we don't link to it, see 
![image](https://github.com/Green-Software-Foundation/state-of-green-software/assets/897523/9bd009fa-a1d7-401c-bcc4-670169247d21)

**To Reproduce**

Visit https://sogs-report.netlify.app/insights/green-software-principles-user-experience/

**Expected behavior**

When we say "SOGS Survey" or refer to our survey we link to it https://sogs-report.netlify.app/survey/

**Comment by Oleg-Zhymolokhov** [comment]
Updated the text to be a hyper-link.
