### ISSUE TITLE
Navbar visual bug on android

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#185]
It appears in chrome on Android 13
![Screenshot_2023-05-31-10-18-05-50_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Green-Software-Foundation/state-of-green-software/assets/125550685/4962c9d8-d34e-4eb4-ae08-7aae73a9933f)

**Comment by osamajandali** [comment]
Fixed!
