### ISSUE TITLE
Reorder SOGS Insights

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/state-of-green-software#192]
What: SOGS Insights
Why: The insights are not listed in order of importance/most valuable and its affecting what visitors are clicking on when they visit the website. 
How: Namrata to review the insights again and propose an order that prioritizes the most compelling/striking insights

Deadline: June 8

**Comment by jawache** [comment]
@NAMRATA-WOKE I think the ordering is great. But I think I misunderstood what you were aiming for when we spoke. There isn't any ability to have different views for different roles on the website and adding something like that would take some time.

What I was looking for was more for a simple and quick reorder for the default order that everyone sees. Currently what you see on landing is random and would be good to display the most impactful insights first.

We could use these as top 10 lists posted as articles or social media posts though, totally see the value of targeted content per audience.

**Comment by NAMRATA-WOKE** [comment]
@jawache you didn’t misunderstand me! I think a simple reorder is what we should do as a first step. I categorized it by audience for internal review based on the audience you want to prioritize. For example, I wasn't 100% sure if you wanted to prioritize insights for business leaders or developers/designers.

**Comment by tamigraph** [comment]
Hi both! Thanks for these categorizations, Namrata. They look spot on to
me. As for the ordering, it just depends on the audience we want to reach.
I'm guessing business leaders or developers are the two most likely target
audiences, right?

**Comment by NAMRATA-WOKE** [comment]
@Oleg-Zhymolokhov @osamajandali can you please reorder based on the following? 

1. [There is a business case for making software greener](https://stateof.greensoftware.foundation/insights/green-software-business-case/)
2. [Green Software is a priority for software practitioners, but still lacks leadership support](https://stateof.greensoftware.foundation/insights/green-software-is-a-priority-for-software-practitioners/)
3. [Measuring carbon emissions is crucial for scaling sustainable AI](https://stateof.greensoftware.foundation/insights/measuring-carbon-emissions-crucial-for-scaling-sustainable-ai/)
4. [Responsible AI is green AI](https://stateof.greensoftware.foundation/insights/responsible-ai-is-green-ai/)
5. [Green Software is vital for a net zero future](https://stateof.greensoftware.foundation/insights/green-software-vital-for-net-zero/)
6. [Software legislation has quadrupled in the last decade](https://stateof.greensoftware.foundation/insights/software-legislation-has-quadrupled-in-the-last-decade/)
7. [Green software is central to tech ethics](https://stateof.greensoftware.foundation/insights/green-software-tech-ethics/)
8. [63% of CEOs do not rate sustainability as a top priority](https://stateof.greensoftware.foundation/insights/63-percent-of-ceo-do-not-rate-sustainability-as-a-top-priority/)
9. [Green software should be part of higher education](https://stateof.greensoftware.foundation/insights/green-software-higher-education/)
10. [92% of software practitioners are concerned about climate change](https://stateof.greensoftware.foundation/insights/92-percent-of-software-practitioners-are-concerned-about-climate-change/)
11. [Open-source solutions are essential to greening software and ICT](https://stateof.greensoftware.foundation/insights/open-source-essential-for-green-software/)
12. [Carbon-aware software is central to decarbonization](https://stateof.greensoftware.foundation/insights/carbon-aware-software-central-to-decarbonization/)

Everything else can follow.

**Comment by Oleg-Zhymolokhov** [comment]
@osamajandali I will reorder this and make a PR

**Comment by zanete** [comment]
@osamajandali will fix the merge conflicts or whatever was the roadblock here

**Comment by osamajandali** [comment]
Done!

**Comment by zanete** [comment]
Amazing, thanks @osamajandali !
