### ISSUE TITLE
Update the LinkedIn Shares

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#194]
Parent issue: #191

Why: When you share an insight page directly on LinkedIn, it does not show the image of the insight, but instead the image that's on the homepage. 

What: Need every insight link share for LinkedIn to correspond to the insight image.

**Comment by zanete** [comment]
Capturing the status on the weekly call:
- this bug is being investigated, only happens on linkedIn

**Comment by zanete** [comment]
Delayed due to travelling, rolling over to next week

**Comment by osamajandali** [comment]
Fixed!
Linkeding cache the urls, so it might take some time to reflect on all the insights.
Here is the a working insights where I cleared cache from it from a linkedin tool
https://stateof.greensoftware.foundation/insights/measuring-carbon-emissions-crucial-for-scaling-sustainable-ai/
