### ISSUE TITLE
Include "Subscribe to the Green Software Foundation Weekly Newsletter" at the bottom of each insight and homepage

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#195]
Parent issue: #191

Sub-text: Get the latest news, insight and information on new tools and resources to help you decarbonize your software.

**Comment by osamajandali** [comment]
are we already have newsletter in each insight page ?

**Comment by zanete** [comment]
if it's not a huge amount, please include on the HP as well.

**Comment by zanete** [comment]
Delayed due to travelling, so rolling over to next week.

**Comment by osamajandali** [comment]
Done!
