### ISSUE TITLE
[REPORT] Preliminary version for COP

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#20]
@Leamsi9 feel free to add your work here for WG review. thanks.

**Comment by holanita** [comment]
WG call: no objections for Ismael to work on this. We will review the progress and decide on feasibility in the next WG call.

**Comment by jawache** [comment]
@Leamsi9 this ticket doesn't have much information so I'm going off what I've heard in meetings regarding this task,

I believe the intention is either;

1) To give people a taster of what the report will contain so they are more likely to signup for the survey/add their email to be notified for the final report.

2) Act as a marketing hook to get some interest in the report in the wider world.

If it's (1) I think given where we are the best return on investment is just to have the outline in the website, so people can see the overview of what the report will contain. That won't take much time at all.

If it's (2) totally agree we need to focus on getting lots of interest in the report and esp. filling out the survey. To that end we need a fully fleshed out marketing plan before the survey launch day. Post launch we'll need to put in an immense amount of effort to get people to our site and fill out the survey. You and Namrata did a great job on the hackathon we need that for this report but this time let's get all the work done early so we are not doing daily firefighting post survey launch to try to get people to the website. Let's get than plan fleshed out now, A marketing plan is a better use of our time to ensure we get traffic to this report.

**Comment by Leamsi9** [comment]
This all makes sense.  Let's discuss in our call today whether we might have more to offer by then, or just want to keep it to the outline (after integrating your revisions).

**Comment by holanita** [comment]
@Leamsi9 shall we archive this task now that you guys are focusing on the outline and the marketing plan in other GH issues? sounds like in the end we will not deliver the preliminary report for COP.

**Comment by jawache** [comment]
@holanita agreed, or at least move this from "in-progress" to "todo" we agreed that we'd only pursue this if there was time and we've got less than 2 weeks to go now.

**Comment by holanita** [comment]
Task remains in waiting/parking status as of today.

**Comment by holanita** [comment]
Remains parked. This is less and less likely to happen seeing the delay on all other tickets @Leamsi9.

**Comment by holanita** [comment]
@jawache do you think I should cancel this one due to lack of time? We never actually wanted to have this report.

**Comment by Leamsi9** [comment]
Yes, I understood we decided not to move forward with this when planning COP

**Comment by holanita** [comment]
Perfect, it was your idea so if you are okay with closing this and I'm happy to close this. Thanks for the confirmation.
