### ISSUE TITLE
Adding Japanese Translations to SOGS website

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/state-of-green-software#200]
NTT Data has [translated SOGS in Japanese](https://drive.google.com/drive/folders/1y6CMMeomSXde6QUBv4k5vn1Wv6hZN0qR?usp=sharing). Is it possible to introduce the translations on the SOGS website?

**Comment by zanete** [comment]
@NAMRATA-WOKE to answer your about what is possible, @osamajandali would need to add handling of language switching / update search etc, and then the translators would ne able to add translations via markdown files and GH Pull requests to any language.

It would be around 2 weeks of focused work and given the current priorities not feasible to tackle right away. 

Also, need to understand whether the effort is justified, e.g. 
- are we going to keep the site for next year as is or change it up? 

Alternatively, we could add another website that is just in Japanese but it wouldn't be generic and only work in Japanese.
@jawache please advise on the direction here.

**Comment by zanete** [comment]
this has been added
