### ISSUE TITLE
Reduce Header Sizes

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/state-of-green-software#204]
**Is your feature request related to a problem? Please describe.**
The header in each insight is a little too large. Takes up too much space on small devices.

**Describe the solution you'd like**
Rethink design to make the height smaller.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by russelltrow** [comment]
What inspiration could we take from a website like Medium? https://medium.com/@andrewthoughts.me/arguing-about-facts-doesnt-work-why-politics-should-be-like-couples-therapy-c5f8856a1127

**Comment by Jenya-design** [comment]
@adamj89 could you please share some screenshots?
This is how I see the insights on my mobile, it looks good to me, considering those are text heavy images
I assume it might take up more space on the tablet

If you want to make the height smaller, I can remove the heading and the logo from the image, it's the fastest option
Maybe drop the illustration lower as in the example by @russelltrow 
@osamajandali could you please advise, what's technically possible here?

![photo_2023-10-04_13-37-39](https://github.com/Green-Software-Foundation/state-of-green-software/assets/69306070/7076e2a6-cbad-405f-8a93-9b770a729f68)

![Insights  SOGS_canva elements-16](https://github.com/Green-Software-Foundation/state-of-green-software/assets/69306070/8069d7db-d2c3-4e78-b5d7-5d56ebec8bc4)

**Comment by osamajandali** [comment]
The best approach to have a good look illustration in all devices is to have 3 kinds of illustration for each illustration, meaning one for mobile, one for tablet and one for desktop.
But I think it doesn't take that much height from in the mobile imo, i believe it should be taller

**Comment by Jenya-design** [comment]
@russelltrow do you think we can close this task? I'm not sure how to move forward with it and if it's still relevant

**Comment by russelltrow** [comment]
Have closed it, we aren't touching SOGS
