### ISSUE TITLE
[SURVEY] Explore Survey Monkey's paid features

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#23]
Investigating the 'buy responses' feature of Survey Monkey. Will be listing prices based on target groups:

UK, Age: 25-60, Industry: IT (UK1 target group) – 30 questions, 200 responses – Price: 5,532 GBP
US, Age: 25-60, Industry: IT (US1 target group) – 30 questions, 500 responses – Price: 6,395 GBP
India, Age: any, Role: software developer (India SD target group) – 30 questions, 100 responses – Price: 2,656 GBP

**Comment by jawache** [comment]
It's a lot cheaper! I think given that we can import the questions into YouGov I propose let's see how the first month goes, if we are struggling to get people to answer in December let's import into YouGov and do a paid service there.

**Comment by Leamsi9** [comment]
See my comments on the marketing doc for a proper analysis of all commercial options. If I we're spending the money my priority would be:

1) Linux Foundation's 4 million database.
2) YouGov international panel
3) Incentives for replies in our own mailing list plus social media spend

**Comment by holanita** [comment]
Putting this on hold for now as per Asim's comment. Let's focus on COP and revisit this later.

**Comment by holanita** [comment]
We need to start exploring this. Moved to To Do!

**Comment by holanita** [comment]
As discussed with Asim, I will be exploring options with YouGov and SM asap. Approved budget: 5K.

**Comment by holanita** [comment]
Next steps:
- [x] review yougov options
- [ ] SM import (not doable) vs SM paid
- [ ] sign up with gsf email account
- [ ] make sure data can be easily exported and imported into Survey Monkey
- [ ] review audience and prices
- [ ] confirm targeting with Tamara 
- [ ] set up and review survey in yougov
- [ ] Sean to set up payment

**Comment by holanita** [comment]
@jawache this has been mentioned in the WG call yesterday and Chris advised we should discuss the financial matters off the call. I will need your guidance on whether (and how much) we can invest into this. Based on the online calculators that Survey Monkey and YouGov have, it could cost a lot more than 5K to get 3000 responses – it might be around 10K or more. I'm in touch with their sales teams to get tailored quotes for exactly what we need. Still waiting for their quotes. If you have a view on this already, please share. (e.g. shall we aim for 1000 responses instead, would 10K be fine for 3000 responses)

**Comment by holanita** [comment]
Cancelled as discussed with Asim today. We are about to close the survey. We have 2100+ responses. Might try paid LinkedIn ads next time.

**Comment by Leamsi9** [comment]
Fantastic news! 2100 responses is a very respectable number.

 Let me know how you want me to access the data so I can begin to
incorporate it into SOGS.
