### ISSUE TITLE
[SURVEY] Upgrade Survey Monkey

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#24]
Why: to be able to add survey completion redirect (customized exit page) and remove SM footer
What: upgrade from Team Advantage (£25/user/month) to Team Premier (£75/user)month) 

@seanmcilroy29 cc: @jawache the page where users land after completing the survey is a Survey Monkey marketing page that looks ugly, noisy and irrelevant so I was thinking it would be nice to be able to customize it. we need to upgrade to be able to do this. the new package would allow us to remove the Survey Monkey branding from the footer too. see pricing and packages [here](https://www.surveymonkey.com/pricing/upgrade/quickview/?ut_source=header_loggedIn). let me know if we can do this.

**Comment by seanmcilroy29** [comment]
@holanita - Survey Monkey upgraded to Team Advantage. This has the additional functionality to support your survey. 
If you need anything else please let me know.

**Comment by holanita** [comment]
@seanmcilroy29 it won't let me customize the survey end page and still asks for an upgrade. See [here](https://drive.google.com/file/d/1CMOckoZl0DPLSE2er_52kg04FyKukjx2/view?usp=sharing). I think we need the Premier one that includes the feature called 'add survey completion redirect'.

**Comment by holanita** [comment]
@seanmcilroy29 we discussed this with Asim and Namrata yesterday and we figured that we should switch our plan asap to make sure we have the feature that we are looking for (SM calls it _survey completion redirect_). 

Why: to redirect respondents to our page or a simple google doc where we can add marketing CTAs
Next steps: can you ask SM to change our pricing package as we don't have the feature that we were looking to add

As to the package we need 
- I understand that we can't sign up for a team plan as we have to pay for 3 users and that would make it £225 per month.
- The Team Advantage plan we now have doesn't offer the above feature anyway so this won't work for us.
- So if it's ok from a financial perspective, let's switch to the **Premier Annual plan which is £119 / month (billed annually)**
- It has the redirect features as per their website - see [this screenshot](https://drive.google.com/file/d/1gRhmy3I9Yo6-oU-UfOewvEtnx6S1bUvp/view?usp=share_link).

cc @jawache

**Comment by seanmcilroy29** [comment]
@holanita - I've just contacted SM customer support to see if they can transfer this account to the Premier Annual plan, as there's currently no option to do this. As soon as they get back to me, I'll let you know

**Comment by holanita** [comment]
Thank you!

**Comment by holanita** [comment]
@seanmcilroy29 please complete the upgrade as soon as you can as on Friday we lost access to the insight into responses. Hopefully survey functionality will not be limited due to the downgrade on Friday, but it would be best to solve this asap. Many thanks.

**Comment by holanita** [comment]
ETA around 5pm today

**Comment by seanmcilroy29** [comment]
@holanita - SM has been upgraded to Premier Annual.

**Comment by holanita** [comment]
thanks @seanmcilroy29 everything looks good in survey monkey, the new feature seems to work fine
