### ISSUE TITLE
[SURVEY] Design 

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#25]
Why: Asim asked that we tweak a bit the look of the [survey](https://www.surveymonkey.com/r/Preview/?sm=0VKpgfUwJtdFhr1nqqhXmmGA6aKcxGyjyjYsY3LoeHVCE0kVd6hw08FPTbZbjm8_2F) in Survey Monkey before the 10th
What: Jenya to spend an hour or two on this before the 10th if possible – see suggested tweaks below

- [ ] tweak the look (colors, fonts, etc.)
- [ ] create a proper cover image for the top to replace the logo

@Jenya-design HI! Do you have experience with designing Survey Monkey surveys? You can go through the entire survey at the preview link mentioned above. You can give me suggestions on how to tweak the colors, fonts, etc and I can do that myself. Or happy to give you access if it's needed. (Let me know if I didn't add this task to your board the right way).

**Comment by Jenya-design** [comment]
Hello @holanita 
Thank you, I'll prepare the cover design and suggestions for the fonts. I think it might be faster as I have no experiene with Survey Monkey and it's a rather minimalistic design piece. If there will be no more urgent tasks, I'll share it with you by Friday

**Comment by Jenya-design** [comment]
Ok @holanita 
please give me the access and I'll check what I can do with the options we have and if we need any paid features. 
Shall I work with the survey in the link directly or better create a copy?
Thank you

**Comment by holanita** [comment]
We have a paid plan and some built-in themes. Just shared the credentials w/Jenya via Slack. No need to create a copy.

**Comment by Jenya-design** [comment]
Hello @holanita @jawache 
Please check the current view of the survey and let me know what you think

I've created a SoGS custom theme, but not sure how easy it'll be to apply to other survey as it's my first experience with Survey Monkey. Our brand font is not available on the platform, so I replaced it with Lato
I was trying to make the dark theme to match the website, but for some reason there was no option to recolor all the elements (or I didn't figure it out yet)

I replaced the header and made sure the logo is large enough on mobile view
File for the illustrations here
https://drive.google.com/drive/folders/17uFbuUCfrfT-gPU7CuUC34hOQ43ZaMsD?usp=share_link

Thank you

**Comment by holanita** [comment]
Hello @Jenya-design great, thanks for the new illustration! I like our dark green a bit more than this light one. Now that you used it for the buttons too, shall we try and use the **dark green for questions text?** Also, I like the light theme, but I'm not sure if Asim wanted to have a more prominent update so let's wait for his feedback. ([link to preview](https://www.surveymonkey.com/r/Preview/?sm=0VKpgfUwJtdFhr1nqqhXmmGA6aKcxGyjyjYsY3LoeHVCE0kVd6hw08FPTbZbjm8_2F))

**Comment by Jenya-design** [comment]
Thank you @holanita 
I didn't use dark green for the text because it's not used on the website, so I was trying to keep survay consistent despite the light theme. I agree, readability isn't perfect, though I think it still works with this font size.

As an option I can show the dark theme, but I think it would be better to make a copy of survey, so you can compare. Is it possible? I can't see this option right away. As I said I didn't like dark theme  too much as the tools are limited and some elements stay white,  but dark bg can give more interesting look and works better with this light green font.

**Comment by holanita** [comment]
Hey @Jenya-design thanks. I think what we have looks good. Note that I used dark green now when adding [a definition](https://drive.google.com/file/d/1YInmcoD5ZYNFFvXHGlyhsKdgSqLGEuNu/view?usp=share_link).

**Comment by Jenya-design** [comment]
Thank you @holanita 
Definition style looks good to me
If you and @jawache don't have additional comments or requests, please close this task

**Comment by holanita** [comment]
Thanks @Jenya-design I'll leave this open so Asim can comment if he wants to. Will close it after COP.

**Comment by holanita** [comment]
@Jenya-design we made some quick edits yesterday evening:
- changed the color of the question text for better readability 
- added some extra notes just below the title
This is good to go now, thanks for your help with this!
