### ISSUE TITLE
[PM] Track KPIs for SOGS

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#26]
**UPDATE: From November 14, KPIs are tracked [in this spreadsheet](https://docs.google.com/spreadsheets/d/1x_R9Z0qIn7WGvSA_tuW2QHiJIOBjlR0OhjzuLg6aFFk/edit#gid=0) will be updated on an ongoing basis.**

Why: to be able to track progress 
What: define measurable/quantifiable KPIs

- [x] I suggest we add and track each KPI [in this spreadsheet](https://docs.google.com/spreadsheets/d/1x_R9Z0qIn7WGvSA_tuW2QHiJIOBjlR0OhjzuLg6aFFk/edit?usp=sharing).
Number of survey respondents: **0**
Number of interviews booked/completed: **0/0**
Number of sections sent for review: **0**
- [ ] did not have time to discuss this on Nov 2 with @jawache & @Leamsi9 
- [ ] @holanita is tracking KPis on a weekly basis in the above spreadsheet

**Comment by holanita** [comment]
@jawache @Leamsi9 pls check my understanding of today's meeting to make sure we are aligned on due dates & next steps

Key discussions:
- Volume: SOGS website will likely be around 5 times bigger than the Q1 report deck (40 substantial slides instead of 8)
- MVP: focus on 4 core sections and work iteratively to ensure we can deliver these even if we run out of time
- Soft deadline: December - complete interviews and evaluate progress
- Very hard deadline: January 13 - complete interviews and evaluate progress

Project stages:
- DESK RESEARCH: 8 (or 16?) weeks to complete desktop research & outline (one section to complete per week)
- INTERVIEWS &SURVEY: the survey and the interviews will run simultanaeously 
- WEBSITE: Osama should be able to start working on this in December as long as Ismael confirms headlines
- DRAFTING: incorporating survey & interviews in January-February, should finish by the week of the last interview
- COMPLETE CONTENT: to be provided section by section (should take 1 day each)
- EDITOR: likely Catherine
- DESIGN: Jenya to create images and infographics
- REVIEW: share with the WG & SMEs so they have the opportunity to review
- CONSISTENCY REVIEW: 2 weeks + approval + edits if needed
- DESIGN & WEB: final tweaks if needed
- PDF: Jenya will create a PDF once the content is 100% finalized

**Comment by holanita** [comment]
As of today (November 14), we made no progress on the interviews and none of the sections of the desk research are available for review yet. We are tracking the number of people who completed the survey though. From now on, [this spreadsheet](https://docs.google.com/spreadsheets/d/1x_R9Z0qIn7WGvSA_tuW2QHiJIOBjlR0OhjzuLg6aFFk/edit#gid=0) will be updated on an ongoing basis.

**Comment by Leamsi9** [comment]
I have updated tickets #49 #50 #52 

>Very hard deadline: January 13 - complete interviews and evaluate progress

Current hard deadline is Jan 21 as per #11 

Does this ticket need to remain open @holanita? It seems to overlap with several other tracking tickets, like #11 specially. If we do close it, we may need to ensure these milestones are captured in #11:

>EDITOR: likely Catherine
DESIGN: Jenya to create images and infographics
REVIEW: share with the WG & SMEs so they have the opportunity to review
CONSISTENCY REVIEW: 2 weeks + approval + edits if needed
DESIGN & WEB: final tweaks if needed
PDF: Jenya will create a PDF once the content is 100% finalized

**Comment by holanita** [comment]
@Leamsi9 there is no overlap. The thing is, I have tried to get some response from you on this ticket 13 days ago, but that response never arrived so I repurposed this ticket for myself to just track KPIs all by myself. It's good though that we finally have a confirmation on deadlines :)

**Comment by Leamsi9** [comment]
Ah I understand, and apologies for the comms: hackathon, children's
illness, spouse away and massive 1 day event commitment conspired against
me! Should be more responsive going forward!

**Comment by holanita** [comment]
OK, no worries. Good to hear that things are getting better now on your end.

**Comment by holanita** [comment]
We haven't made progress on the desk research and interviews for a long time. Asim suggested we try working in weekly sprints, but it doesn't seem to  work either. I'm closing this ticket as we keep trying new ways and none of them work, so we'll just end up having way too many tickets.

**Comment by holanita** [comment]
Note: I'm still tracking KPIs [in this spreadsheet](https://docs.google.com/spreadsheets/d/1x_R9Z0qIn7WGvSA_tuW2QHiJIOBjlR0OhjzuLg6aFFk/edit#gid=0)  on an ongoing basis.
