### ISSUE TITLE
[SOGS] Create illustrations and icons for the website

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/state-of-green-software#31]
**Why**: To complete the State of Green Software website (https://www.figma.com/proto/B25vyo3My1SzrksFUe2B4p/GSF-Landing-Pages?page-id=664%3A157&node-id=664%3A719&viewport=111%2C547%2C0.26)
**What**: Produce missing illustrations and icons 
**Scope of work**:
- [ ] 4 Illustrations for sections in the screens below
- [ ] 3 icons for for sections in screens below
![image (14)](https://user-images.githubusercontent.com/35653799/199689862-db1c4f8b-1240-4d2c-914e-437b4bf0800e.png)
![image (13)](https://user-images.githubusercontent.com/35653799/199689869-de78f4b0-859c-4af3-a036-2db26834fdff.png)
![image (12)](https://user-images.githubusercontent.com/35653799/199689881-fb8cd226-5f7c-40f5-9fca-d9887eb3fde5.png)

**Comment by Jenya-design** [comment]
Hello @osamajandali @zanete 

Please check the update below
For the header I've created two square illustrations to put on the sides of existing composition, 
@osamajandali please let me know if it can work or I better ajust for one square illustration with the logo in it's center

[Icons preview](https://drive.google.com/file/d/1ineVQHEHnV3G0moKiqeaDZAzCqgzarJg/view?usp=share_link)
1. for developers
2. for business
3. for guiding

folder (svg files are saved without bg)
https://drive.google.com/drive/folders/1uH7ir0XlMpHnMJBTKtp8690dpcro5gcr?usp=share_link


[Illustrations preview](https://drive.google.com/file/d/1Yp-fh8GFDUeY0jNu0qGTaWeGhRR3sMBg/view?usp=share_link)
1-3 header
4 what is GS
5 there is growing ...
6 the stae of GS
7 how can you benefit (shapes and fills adjusted)
8 what kind of information 

folder (svg files are saved without bg)
https://drive.google.com/drive/folders/11DDDG0jbPAwFbUVDqeRxYXDROFkYPTv_?usp=share_link

Thank you

**Comment by osamajandali** [comment]
@Jenya-design Thanks so much; they look fantastic!
The only thing I will not go with is the illustrations around the logo and title because we will have to keep in mind that this is desktop, and there will be a responsive table and mobile views..so it's not a good idea to put illustrations around it.
I suggest giving the logo icon additional green elements to provide the design with a vibe while keeping the original logo, so you don't change it anywhere else.

**Comment by osamajandali** [comment]
@Jenya-design I edit the page and the first section now needed an illustration..
https://www.figma.com/file/B25vyo3My1SzrksFUe2B4p/GSF-Landing-Pages?node-id=725%3A3547

**Comment by Jenya-design** [comment]
Thank you @osamajandali 
Ok, noted about the illustrations for the top. I'll sned you the update for it and for the 1st section in 2-3 hours

**Comment by Jenya-design** [comment]
@osamajandali please check the update
pdf preview https://drive.google.com/file/d/1NWMvkVg8mfvkKUNIIUY_YT56tXzt7s1U/view?usp=share_link
all files https://drive.google.com/drive/folders/11DDDG0jbPAwFbUVDqeRxYXDROFkYPTv_?usp=share_link

**Comment by osamajandali** [comment]
Thank you @Jenya-design 
I tried the logo with those illustrations, but unfortunately, it didn't work well.
I suggest keeping it as it is, or we can choose to tweak it as I did here.


![Image](https://user-images.githubusercontent.com/13832392/200124347-5cba1b63-e040-4dee-a52b-d33e395f18ba.png)

**Comment by Jenya-design** [comment]
Thank you @osamajandali 

I really like the design you've made, but I would suggest we keep the old look if it's not possible to add the illustrations around or wide adaptive banner on top.
Currently we have [this system](https://drive.google.com/file/d/14amiF9ChnhC8xFDyI-iqhia7NJ8OIbAG/view?usp=share_link) approved for wg and project logos. You can see State of GS is consistent with  Policy WG and each WG has it's marker color.

I see that there are various situtaion where you have to tweak the logos to fit the webpage design. I would like to discuss it with you and @jawache for my guidelines task and adjust the design for your needs, but to do it in complex. This way we won't have our brand look all over the places in future, GSF structure is already quite complex. Does that make sense?

@jawache what do you think?

**Comment by jawache** [comment]
Ahh thanks, let's keep it as is then for now @osamajandali and @Jenya-design we can revisit post COP 😃

**Comment by osamajandali** [comment]
@Jenya-design I agree
let's revisit post COP as @jawache was saying
So we are done here I am going to close this
