### ISSUE TITLE
[INTERVIEWS] Build questionnaire

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#32]
Why: to make sure the outcomes of the interviews are consistent and interviews run smoothly
What: create a questionnaire and use it to guide the conversation

Next steps:
- [x] Ismael to draft questionnaire
- [x] Team to discuss 
- [ ] For those who want to do the interview async, we could turn this into a survey in Survey Monkey.

**Comment by Leamsi9** [comment]
Will get to this by Friday!

**Comment by holanita** [comment]
@Leamsi9 please give us an update on this before today's WG call. This has been pending for a very long time.

**Comment by holanita** [comment]
@Leamsi9 in the last 25 days you haven't even replied. Can you tell us something? Anything? :)

**Comment by Leamsi9** [comment]
Survey questions will be ready today.

**Comment by holanita** [comment]
@jawache I'm reassigning this to you. please check the document and the comments.

**Comment by jawache** [comment]
For ref: @holanita I've reviewed and they look good - I tried them out today already on a call with an SC member.

**Comment by holanita** [comment]
OK. Closing and adding the link to this issue: https://github.com/Green-Software-Foundation/state-of-green-software/issues/83
