### ISSUE TITLE
[REPORT] Readers' panel

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#33]
Why: to facilitate the review and give volunteers the opportunity to contribute (the idea comes from a recent call with Avanade)
What: create a readers' panel who will regularly review the content

Next steps:
- [x] Discussed in the team call with Tamara and Ismael on Nov 4
- [ ] Ismael & Tamara to suggest panelists
- [ ] Ismael to share new content periodically (likely in a google document)
- [ ] Panelists to review content and add comments to the google doc

KPI: 5 panelists for each section

**Comment by holanita** [comment]
It might be time to put this on the back burner seeing how much all your other tasks are behind schedule @Leamsi9. What do you think?

**Comment by holanita** [comment]
@jawache do you think it makes sense to work on this? Shall I cancel due to lack of time and action on Ismael's end?

**Comment by Leamsi9** [comment]
Laurent Devernay has agreed to be a reader (lead author of https://almanac.httparchive.org/en/2022/sustainability, I am waiting for confirmation from Avanade, but they had already expressed an interest in principle in doing this, so I would expect that to be in place this week. It would just be a matter of giving them comment access to a copy of the doc and soliciting comments 2-3 times between now and completion. I thought that GS, given their interest in contributing, might also be up for being readers. Could do with one more, academic voice, which I'm sure Tamara could source.

**Comment by holanita** [comment]
@Leamsi9 do you have capacity to drive this? I'm afraid I won't have any due to the delay. cc @jawache

**Comment by jawache** [comment]
This function really should be managed by the Policy WG members and driven by Chris and Elise to either volunteer to read or ask people from inside the WG to volunteer.
