### ISSUE TITLE
Save all SOGS design assets in one folder

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#40]
What: make sure each design asset that has been created so far is saved in one folder on the drive
Why: so Namrata has everything in one place and can look for assets there when needed
When: asap as we need to start marketing the course asap

- [x] Jenya to review what assets we have already
- [x] Jenya to put them all in one folder
- [x] Namrata to review what we have and confirm if she needs anything else urgently
- [x] Jenya to confirm here availability in case what we have is not enough

**Comment by holanita** [comment]
@Jenya-design please do the first two tasks asap and let us know what your availability looks like these days and moving forward until the end of December. many thanks! cc @NAMRATA-WOKE

**Comment by Jenya-design** [comment]
Hello @NAMRATA-WOKE @holanita 

Please review the assets here
https://drive.google.com/drive/folders/1nQq9G49GbT91lS6Zq6nnMTHQwjGkHyMU?usp=share_link

There are very few assets created specifically for SoGS but I can adjust other GSF assets to SoGS fairly quickly
Please let me know what you need for marketing. If possible please give me the total list of the design positons you might need for the SoGS: presentation template, guidelines, canva templates etc

I assume SoGS tasks will be my priority after I finish the illustration for the Book of News today
I will aim to give you all marketing materials before Osama starts working with the website in December 
I'll share the days when I'm away in Nov-Dec a bit later in slack
Thank you

**Comment by holanita** [comment]
@Jenya-design thanks. Namrata might actually need some images for social media and other marketing activities fairly soon meaning within a couple of days. let's wait for her to review your folder and confirm what else she needs

@NAMRATA-WOKE I've added the url to the [assets list](https://github.com/Green-Software-Foundation/state-of-green-software/issues/41)

**Comment by holanita** [comment]
@NAMRATA-WOKE were you able to look at the assets Jenya shared? Please confirm if you need anything else or lmk if we can close this task.

**Comment by holanita** [comment]
@Jenya-design since the task has been created, I'm closing this ticket now. Please just make sure to save any new assets in the folder you shared with us here. Many thanks.
