### ISSUE TITLE
Confirm SOGS content for newsletter due on Nov 15

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#42]
What: confirm what content should be added to the upcoming newsletter about SOGS 
Why: to optimize our marketing efforts

Suggested next steps:
- [x] Namrata to suggest content
- [ ] Asim to review and approve
- [ ] Namrata to make sure content is added to the newsletter

Related tickets:
- https://github.com/Green-Software-Foundation/ops-content/issues/12 (this is where we can discuss the entire newsletter, not just SOGS)

**Comment by holanita** [comment]
@NAMRATA-WOKE @jawache we don't have a process for the newsletter yet. let's just use this ticket to discuss what content will go into the next issue about SOGS

**Comment by NAMRATA-WOKE** [comment]
My recommendation for what to include:

- Why we're doing a survey
- Audience for the survey 
- time commitment (5 minutes?)
- what to expect once they fill out the survey 
- request to share the survey with fellow software practitioners 
- if folks have feedback about the survey, who can they contact? 
- decarbonize event banner at the bottom of the email that hyperlinks to the landing page

**Comment by holanita** [comment]
Sounds good to me. For feedback and questions, can they contact help@greensoftware.foundation?

**Comment by NAMRATA-WOKE** [comment]
Who manages that inbox?

**Comment by holanita** [comment]
Steph and Sean AFAIK. This is what we use for other projects. Asim wanted each inquiry to go through the helpdesk from now on. Alternatively, we could use this gsfsurvey@greensoftware.foundation as incoming emails are FWed to me. TBD.

**Comment by holanita** [comment]
Let's try to discuss with Asim in our weekly marketing call today.

**Comment by holanita** [comment]
@jawache shall we try to send this out tomorrow according to the original plans? Namrata has no access to Mailchimp yet, want me to go ahead and create a new simplified layout for the newsletter or do you want to get involved?

**Comment by holanita** [comment]
@NAMRATA-WOKE fyi the newsletter might go out on Wednesday especially if the hackathon blog post is going out tomorrow. Asim will put together this issue. Some content had been added to [this document](https://docs.google.com/document/d/1kWvG2KemEKXXTeUwe8qmMUeN_BOWoDHpKdo-RueSlM4/edit#) already.

**Comment by holanita** [comment]
Newsletter went out today. Next week we need to figure out the process so Urs and/or Namrata can take this over from Asim. Will add a new task to the new agenda tomorrow.

**Comment by holanita** [comment]
Marking this closed as Asim sent out the external newsletter yesterday in the end. To be continued here:
- https://github.com/Green-Software-Foundation/state-of-green-software/issues/64
