### ISSUE TITLE
Confirm banner content and placement 

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#44]
What: we will replace the Hackathon banner with a SOGS banner
Why: to promote SOGS after COP
When: we will update the banner **on Nov 11**

What we need:
- [ ] Asim to confirm if this banner will be placed all over our webpages or on specific pages only
- [x] Asim/Namrata to confirm copy for the banner
- [x] Asim/Namrata to confirm is we need a shortened url for this
- [ ] Anita to work with Jenya to create an image for the banner
- [ ] Osama to replace the banner once all the assets are available

**Comment by holanita** [comment]
@NAMRATA-WOKE @jawache pls confirm the first two bulletpoints above so I can start working with Jenya and Osama on this.

**Comment by holanita** [comment]
@NAMRATA-WOKE can you proceed without Asim's input. It would be nice to change the banner asap.

**Comment by NAMRATA-WOKE** [comment]
Yes I'll create something with the existing illustrations.

**Comment by NAMRATA-WOKE** [comment]
Can someone confirm which link to use for the banner?

OPTIONS:

grnsft.org/sogs/survey
stateof.greensoftware.foundation

Thanks. My recommendation is the direct link: grnsft.org/sogs/survey

**Comment by NAMRATA-WOKE** [comment]
[](url)
![SOGS Survey - Twitter Header (1)](https://user-images.githubusercontent.com/114516498/201411143-a75dba28-ac90-4611-a46d-c45f868ed3e9.png)

**Comment by holanita** [comment]
Hello @NAMRATA-WOKE there might be a misunderstanding here. What we mean by banner is the one at the top of our website.  It's a lot narrower. See below. It will be placed on some/all of our pages, this is still to be confirmed by Asim. What you pasted above might be what we need as a social cover image. Let's discuss the details in the call today.

![Image](https://user-images.githubusercontent.com/100846607/201621338-25d0bac0-d4af-43e4-8d39-64c5e765d522.png)

**Comment by NAMRATA-WOKE** [comment]
Ah! I can modify this one to highlight the survey but need the specs from @osamajandali and preferably the link to the original art file from @Jenya-design. Can get this done today.

**Comment by Jenya-design** [comment]
Hello @NAMRATA-WOKE @holanita 
original file for the banner is here
https://drive.google.com/drive/folders/1FoI_8f2Z-hdGu-0xj6aiaTtxB3lsUgMK?usp=sharing
I made it as ai / svg file, not canva design, size 1920x100 px
Please create the ticket if you need my help with this task

**Comment by holanita** [comment]
Just discussed with Namrata. 
- I'll create a task for Jenya. 
- Url should be grnsft.org/sogs/survey
- copy 1 for banner: 
Be part of the largest green software survey ever  
Survey ends 31 December 2021 (we can shorten December to Dec if needed)
Button: Take Survey Now [grnsft.org/sogs/survey] 
- copy 2 for banner: 
Help us understand the state of green software. 
Button: Take Survey Now [grnsft.org/sogs/survey]

**Comment by holanita** [comment]
Closing this ticket, as the task is now with Osama. Url and image have been shared with him.
