### ISSUE TITLE
Add a note to Survey Monkey that our survey is anonymous

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#45]
What: this ticket is to discuss whether we should add a note to the SOGS survey that it is anonymous
Why: this has been suggested by Namrata [here](https://www.figma.com/proto/B25vyo3My1SzrksFUe2B4p?node-id=725:3547#301617885) while discussing the landing page 

As of today, it is not obligatory for respondents to indicate their personal details. At the very end of the survey, they can opt in to receive further follow up questions and for this they have to indicate their **email address**. But again, this is optional. Let's discuss whether it's worth adding a note to the first page of the survey. Maybe to the text right underneath the title - see [here](https://www.surveymonkey.com/r/Preview/?sm=0VKpgfUwJtdFhr1nqqhXmmGA6aKcxGyjyjYsY3LoeHVCE0kVd6hw08FPTbZbjm8_2F).

Next steps:
- [ ] Asim & Namrata to discuss and decide
- [ ] Anita to make sure this is discussed with the survey team if needed

**Comment by holanita** [comment]
@NAMRATA-WOKE @jawache pls discuss and let me know your decision so I can take action accordingly.

**Comment by NAMRATA-WOKE** [comment]
If we are asking for email addresses which disclose a person's identity, we should somewhere (SOGS landing page) or the bottom of the survey indicate if the responses will be anonymized during reporting or aggregated based on the institution. The decision should line-up with how the report is being approached from a content category perspective. If knowing who filled out the survey adds little/no value to the report, no need to ask for it!

@jawache @Leamsi9

**Comment by holanita** [comment]
As per our discussions with Asim on Friday, this will not be necessary. Ticket cancelled.

**Comment by holanita** [comment]
As per our discussion with Asim on Friday, this will not be necessary. Let's revisit briefly in our call today.

**Comment by holanita** [comment]
As discussed with Namrata, anyone who includes their email address should be aware that their feedback will not be shared with any third parties.

**Comment by holanita** [comment]
I can't edit the survey right now as our Survey Monkey account has not been upgraded yet, but once that is done, I'll add a note to Q26 that _'We do not share individual-level data or survey responses with third parties without asking for and receiving your explicit permission.'_

**Comment by holanita** [comment]
This is now done. Had to tweak the text and the setup slightly.
<img width="849" alt="Screenshot 2022-11-15 at 9 59 50" src="https://user-images.githubusercontent.com/100846607/201875827-180712db-16e2-494a-812b-aed018e1e307.png">
