### ISSUE TITLE
Add cover images to social channels

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#47]
What: as discussed yesterday, new cover images will be added to linkedin, twitter and the podcast (?)
Why: to promote SOGS after COP
Who: waiting for Jenya to confirm her availability, but Namrata can do this if needed
When: on Friday, Nov 11

Next steps:
- [x] Jenya to confirm her availability on another ticket
- [ ] Namrata to proceed if Jenya is not available OR
- [ ] Anita to add ticket to Jenya's board if she can work on this

**Comment by holanita** [comment]
@NAMRATA-WOKE can you proceed without Jenya? Let me know if you need any support with this.

**Comment by NAMRATA-WOKE** [comment]
Yes.

**Comment by holanita** [comment]
@NAMRATA-WOKE you might have closed this by mistake. I can still see the Hackathon cover image on Twitter for example. 
<img width="866" alt="Screenshot 2022-11-14 at 10 34 45" src="https://user-images.githubusercontent.com/100846607/201625647-e3cf557a-aaa5-4991-8700-9f4ac2eacc77.png">

**Comment by holanita** [comment]
@NAMRATA-WOKE looks like our twitter and linkedin covers are now updated. Is there anything left to do here?

<img width="1237" alt="Screenshot 2022-11-16 at 12 07 19" src="https://user-images.githubusercontent.com/100846607/202164661-85bcf880-0833-4544-ba9e-8016d57b4e69.png">

**Comment by NAMRATA-WOKE** [comment]
No we can close this!
