### ISSUE TITLE
Desk research for knowledge

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#49]
What: finalize the desk research for the knowledge section
Who: Ismael
When: Nov 17

**Comment by holanita** [comment]
Might be delayed as [this first one](https://github.com/Green-Software-Foundation/state-of-green-software/issues/48) is delayed too.

**Comment by Leamsi9** [comment]
Desk research is about 50% complete. Likely delayed by 1-2 days for website ready v.0.1 (excluding survey and interview data)

**Comment by holanita** [comment]
Just adding a note here that this is 11 days behind schedule.

**Comment by holanita** [comment]
@Leamsi9 just a reminder that @jawache asked that you continue with TOC once the business case is done. Content should be added to [this google document](https://docs.google.com/document/d/1cgy-38nOnW3L98d7mr4OnInHVxKpR2zd/edit). This is urgent as we are very much behind schedule. What is your ETA?

**Comment by Leamsi9** [comment]
If that's OK, I will move to Culture first, as it is closer to done, desk research wise, and the Knowledge one may change from interview input. 

In order to keep Asim's comments I had to make a copy of that doc, so he new, equivalent doc containing the whole report is: https://docs.google.com/document/d/1ahV9DCoS16rIJXF1c4-6wYf9sNcIXUxrFEfibW4Q54c

**Comment by holanita** [comment]
@jawache fyi

**Comment by holanita** [comment]
ETA _Dec 16_ as per Ismael

**Comment by Leamsi9** [comment]
Here is the latest version of knowledge reshaped as per @jawache 's specifications for insights and findings. I will keep tweaking and refining in the coming days, but this allows the website to be populated. 

https://docs.google.com/document/d/19fsrUutANbB4J9PLfcFLOrMpw9wTugxjtMXARFyWL8Q/edit?usp=drivesdk

**Comment by Leamsi9** [comment]
One further question @jawache is about length of treatment vs. number of insights. I could break up several of the longer sections here into several smaller insights, or keep it as is, where a single insight gets quite an extended treatment.

**Comment by jawache** [comment]
It all depends on the insight itself, if you can create two _compelling_ insights from one larger one then I'd say yes.

I've scanned the draft the second one has a great title, the first I would suggest word smithing with Namrata later.

Given the timescales I'd suggest getting the drafts out as is and we'll review once everything  has been incorporated.

**Comment by holanita** [comment]
In order to simplify things a little bit, I'm closing these individual tasks and will only have one task where I'll summarize all the essential details briefly. Hopefully this helps.

So for the Knowledge section:
- [This](https://docs.google.com/document/d/1ahV9DCoS16rIJXF1c4-6wYf9sNcIXUxrFEfibW4Q54c) s a new, equivalent doc containing the whole report. Unsure if Ismael is still updating this.
- [Latest version of knowledge](https://docs.google.com/document/d/19fsrUutANbB4J9PLfcFLOrMpw9wTugxjtMXARFyWL8Q/edit?usp=drivesdk) reshaped to include insights and findings. 

Please continue the convo in comments. Hopefully that will make things a bit easier.
