### ISSUE TITLE
Confirm deadlines with Ismael

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#52]
what: deadlines relating to the desk research and the drafting of the report
why: to make sure we are all aligned on what is next and what is doable
when: asap, ideally tomorrow but before the next WG call at the latest

Next steps:
- [x] Ismael to comment on this ticket and confirm if the deadlines listed [here](https://github.com/Green-Software-Foundation/state-of-green-software/issues/11#issuecomment-1301762474) are fine
- [x] discuss deadlines in upcoming team/wg meetings if needed
- [x] Anita to update deadlines if needed

Latest comment from Ismael on Nov 4:
Only comments I'd make would be that Asim & Sean helping land big names should begin this month. Likewise my running the interviews will happen between this month and 21 Jan. 21 Jan is the absolute deadline for the last interview to happen, but our goal is to get then all done by December, and stretch the deadline for exceptions then. So we need a different kind of milestone (and more granularity) on how we mobilise Asim, Sean and the Steering Group this month to secure top level interviews.

**Comment by Leamsi9** [comment]
I'm happy with the deadlines suggested in the #11 checklist, and will try and catch up with the delayed milestones.

**Comment by holanita** [comment]
@Leamsi9 awesome saving a copy here for our future reference. I only opened this ticket because it has been really difficult to get a reply from you, so it became a whole task for me to chase you :) It's fine now, thanks for your confirmation.
<img width="905" alt="Screenshot 2022-11-15 at 16 33 23" src="https://user-images.githubusercontent.com/100846607/201960189-89d15e3d-a339-4e51-b7c0-aa4d34160abf.png">
