### ISSUE TITLE
Clarify short links (and corresponding Survey Monkey collectors)

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#54]
Why: to minimize the number of shortlinks but still ensure we can track progress in each relevant segment
What: Namrata and Anita to align on what urls we need

These are the segments Asim would like to have in the report:
- [x] Social (this has been set up in Survey Monkey, no responses received as of Nov 14)
- [x] Members (set up in Survey Monkey, receiving responses since Nov 10)
- [ ] Internal (Email, slack announces etc...)
- [ ] Newsletter
- [ ] Meetup
- [ ] Partners
- [ ] + direct traffic from the website

**Comment by holanita** [comment]
External for social:
- .../member-external Members to promote survey in their social channels (one custom link for all the members?)
- 1 collector for social is enough 

GSF short links for social (do not split up, they are members too)
- linkedin
- twitter
- email (newsletter)

Meetup - we only engage the community if we do a webinar (create collector later?)

**Comment by holanita** [comment]
Now that I have access to short.io, I'll take care of this myself to keep things simple. Links will be listed [here](https://docs.google.com/spreadsheets/d/1yYhCH8hvC-pSbJ0RZVkIPzWzMOE41VT5MKj1PQoexVA/edit#gid=0).

**Comment by holanita** [comment]
@NAMRATA-WOKE I've added a couple of comments for you in the doc as some links don't seem to be set up consistently

**Comment by NAMRATA-WOKE** [comment]
Will take a look today.

**Comment by holanita** [comment]
@NAMRATA-WOKE lmk when you have news on this. I'll be off for a few days so it would be nice to figure this out today. 

Maybe working with comments in the google doc doesn't work for you so let me ssummarize everything here:

1. I've linked the **newsletter** one to Survey Monkey and I can already see conversions as it was used [in this email](https://mailchi.mp/greensoftware/decarb-software-goes-live-in-1h-9235201?e=5e94464af0) recently. 
2. Not sure what this is for: https://grnsft.org/PvDmP7 but doesn't look like a user-friendly url. Can we remove this?
3. What are you going to use this for?  https://grnsft.org/sogs/survey/member-twitter 
4. What are you going to use this for? https://grnsft.org/sogs/survey/member-linkedin
5. What are you going to use this for? https://grnsft.org/sogs/gsf-member
6. The CNFC one we don't need yet, as it hasn't been decided if we track partners one by one or not. Let's wait a bit.
7. This one https://grnsft.org/sogs/survey/social is linked to our Linkedin collector in Survey Monkey. We came up with the idea of using this on Nov 10, but I can't see any conversions yet. Are you using this for LinkedIn?
8. This one https://grnsft.org/sogs/survey/twitter I could link to our Twitter collector in Survey Monkey and this would allow us to track conversions. But for this I have to remove your original url in short.io so please confirm if that's ok with you. 
9. The rest is fine. The ones without title were created by Asim/Steph one by one for each of our members.

I remember you mentioned you wanted members to track their social media activity. If that's what 3, 4 and 5 are for, I'm not sure we can ask them to be that granular. Can we simplify this?

I think it's mostly the social ones which look really confusing. Let's try to simplify all of this a bit and make things more obvious so we all know what we are looking at. Let's also avoid creating links which are not needed (yet).

**Comment by holanita** [comment]
@NAMRATA-WOKE hey thanks for the call. so here is the final list of short links:

**For members:**
Internal: remind them to use the link that Asim had shared with them or they can contact me if they don't have it
External: they can use this one for each of their external channels: https://grnsft.org/sogs/survey/member-external

**For us internally:**
Newsletter: https://grnsft.org/sogs/survey/newsletter
Linkedin: https://grnsft.org/sogs/survey/linkedin
Twitter: https://grnsft.org/sogs/survey/twitter

These are all linked to collectors in Survey Monkey so we will be able to track conversions for each of them 👍 

(The only thing that is missing is 'partners'. Will check with Asim if he wants to track their conversions one by one.)

**Comment by holanita** [comment]
Closing this. From now on, I'm tracking conversions ([here](https://docs.google.com/spreadsheets/d/1yYhCH8hvC-pSbJ0RZVkIPzWzMOE41VT5MKj1PQoexVA/edit#gid=0) and [here](https://docs.google.com/spreadsheets/d/1yYhCH8hvC-pSbJ0RZVkIPzWzMOE41VT5MKj1PQoexVA/edit#gid=0)). Short link for partners will be discuss on the other ticket if needed.
- https://github.com/Green-Software-Foundation/state-of-green-software/issues/43
