### ISSUE TITLE
Create SOGS banner for website

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#55]
What: create new banner for the website
Why: to promote SOGS
When: asap

@Jenya-design we would like to replace the current Hackathon banner at the top of the website with a new one that promotes SOGS. We have two copy options for you, the second one is a bit shorter. Do you have capacity to work on this asap?

copy 1:
Be part of the largest green software survey ever
Survey ends 31 December 2021 _(you can shorten December to Dec if needed)_
Button: Take Survey Now 

copy 2:
Help us understand the state of green software
Button: Take Survey Now

As discussed with @NAMRATA-WOKE [here](https://github.com/Green-Software-Foundation/state-of-green-software/issues/44).

**Comment by Jenya-design** [comment]
Hello @holanita 
Thank you for creating the ticket, I'll share the update tomorrow as early as possible

**Comment by Jenya-design** [comment]
Hello @holanita @NAMRATA-WOKE 

Please review the update here
https://drive.google.com/drive/folders/1t-Ow-EdnpYyZwPuOMXwDSAUp8BAf2cyw?usp=share_link
I used copy 2 as it's shorter 
Thank you

**Comment by holanita** [comment]
Hey @Jenya-design thanks for your quick action :) I like the design and I agree that the text should be short. I think I'd prefer the first copy though. How about replacing 'Help us understand the state of green software' with 'Be part of the largest green software survey ever'? @NAMRATA-WOKE what do you think?

**Comment by Jenya-design** [comment]
@holanita @NAMRATA-WOKE 
Please check the update v02 (I left the previous version as v01 just in case). Formats png and svg for both
https://drive.google.com/drive/folders/1t-Ow-EdnpYyZwPuOMXwDSAUp8BAf2cyw?usp=share_link

**Comment by NAMRATA-WOKE** [comment]
I would remove the "state of green software" middle text and make the Take the Survey button more center-eye and add the "ends 31 Dec" to add a sense of urgency.

**Comment by holanita** [comment]
@Jenya-design as we didn't hear form Namrata, please create the asset based on her instructions and ignore my last message. We don't have more time to wait as we wanted to update the website banner by last Friday. Thanks!

**Comment by Jenya-design** [comment]
Thank you @holanita @NAMRATA-WOKE 

Please review new options here
https://drive.google.com/drive/folders/1t-Ow-EdnpYyZwPuOMXwDSAUp8BAf2cyw?usp=share_link
I updated the design according to the last comment by @NAMRATA-WOKE, but there's one additional issue . From design point it doesn't makes sence to use only the icon for SoGS (withouth 'state of green software' wordmark) along with the complete GSF logo. Use two icons with 'by' between them is also odd.

so I made two options:
v01 - both logos (full versions)
v02 - I removed GSF logo and kept only SoGS icon

Let me know what you think

**Comment by holanita** [comment]
Many thanks @Jenya-design let's use the second one that looks a bit more simple. I'm closing this task and creating a new one for Osama so we can get this up on the website quickly.
