### ISSUE TITLE
Create social cards for SOGS

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#56]
What: create social cards for Linkedin and Twitter
Why: to promote SOGS
When: by Thursday if possible

As metioned by @NAMRATA-WOKE [on this ticket](https://github.com/Green-Software-Foundation/state-of-green-software/issues/40).

@Jenya-design please create social cards for Twitter and LinkedIn to promote the survey. 
- Namrata had created [one as an example](https://www.canva.com/design/DAFR5RMPZLY/BpB86kWGrwHK9mcBpnzlag/edit?utm_content=DAFR5RMPZLY&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton).
- Use [these pre-drafted posts](https://docs.google.com/document/d/1BZk16PONxDKKl4vN2w2qJP72pncV1v0Pe06z-vQC4yw/edit#bookmark=kix.ecnrep8g7qkh) to inspire the posts.
- The link featured in all the posts should be: grnsft.org/sogs/survey

If you can create these social cards by Thursday, that would be great!

**Comment by Jenya-design** [comment]
Thank you @holanita @NAMRATA-WOKE 
Please open the access to the dec with pre-drafted posts (I've sent the request)
I'll share the update on Thursday as you requested

**Comment by holanita** [comment]
@Jenya-design I'm not the owner but I was able to send you an email and allow you to comment I think. Please double check whether it worked.

**Comment by Jenya-design** [comment]
Hello @holanita @NAMRATA-WOKE 
Please review the update for canva templates

[Twitter posts 1600 x 900](https://www.canva.com/design/DAFSIrO24Bg/l-UTipvO4uCiU94ARk5EXg/edit?utm_content=DAFSIrO24Bg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

[LinkedIn posts 1200 x 1200](https://www.canva.com/design/DAFSJU_PyyY/Z_AC1OT1-aa4mQuko_xLiA/edit?utm_content=DAFSJU_PyyY&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

canva folder with all elements
https://www.canva.com/folder/FAFSM-YIxj4

Please let me know if you need any adjustemrnts done today, I'll be away tomorrow and back to work on Tuesday
Thank you

**Comment by holanita** [comment]
Thanks a lot Jenya – @NAMRATA-WOKE please review this today so Jenya can still make edits if needed.

**Comment by holanita** [comment]
Closing this, as we haven't heard from Namrata, but Jenya is out of office already. We can open another ticket if needed.
