### ISSUE TITLE
Create custom exit page for Survey Monkey

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#57]
Why: those who complete the survey should be redirected to a custom exit page
What: create customer page

Steps:
- [x] finalize copy 
- [x] create visuals if needed
- [ ] Osama/Asim to build a simple page

Copy suggested by Asim [here](https://github.com/Green-Software-Foundation/state-of-green-software/issues/46#issuecomment-1311912938)

- Share the survey to your audience (Click to Tweet, Linkedin, Facebook)
- Sign-up for our newsletter.
- Join our Meetup.
- Take our course
- Join our discord.
Perhaps a drip feed campaign via email._

**Comment by holanita** [comment]
@jawache I've created this ticket based on what we discussed on Friday. I recall you mentioned this would be easy to create in the CMS? So wondering if you want to do this yourself or if I should work with Osama on this?

**Comment by holanita** [comment]
@jawache see above. Osama was out of reach for a while, but he seems to be back now so if you want him to do this, I can work with him from next Wednesday.

**Comment by jawache** [comment]
@osamajandali is there a quite way we can add another page to the SoGS website, that might be best - very quick and fast please :) 

**Thank you so much for completing the survey!** 

Sign up below if want access when it's released.
(The same form as is on the SoGS website)

Share this with friends, family members or on social media

Email Link - mailto:?subject=Do%20you%20want%20to%20make%20a%20difference%20for%20the%20environment?&body=State%20of%20Green%20Software%20is%20the%20first%20report%20to%20map%20the%20green%20software%20ecosystem,%20from%20key%20stakeholders%20to%20regulatory%20frameworks,%20from%20impact%20metrics%20to%20academic%20literature,%20open%20source%20tooling%20to%20actionable%20design%20patterns.%0A%0AYou%20can%20help%20make%20a%20difference%20by%20taking%20the%205%20minute%20survey%20and%20contributing%20your%20knowledge.%20Your%20input%20will%20help%20us%20develop%20a%20better%20understanding%20of%20how%20we%20can%20reduce%20CO2%20emissions%20by%20developing%20green%20software.%0A%0A%0AClick%20this%20link%20and%20take%20the%20survey%20now!%20https%3A//stateof.greensoftware.org
Facebook Link - https://www.facebook.com/sharer/sharer.php?u=https%3A//stateof.greensoftware.org
Twitter Link - https://twitter.com/intent/tweet?text=You%20can%20help%20make%20a%20difference%20by%20taking%20the%205%20minute%20survey%20and%20contributing%20your%20knowledge%20to%20the%20State%20Of%20Green%20Software%20Report.%20Take%20the%20survey%20now!%20https%3A//stateof.greensoftware.org
LinkedIn Link - https://www.linkedin.com/shareArticle?mini=true&url=https%3A//stateof.greensoftware.org

Take our free Green Software Practitioner Training 

(Link to learn.greensoftware.org with perhaps an image.

**Comment by zanete** [comment]
@jawache @holanita please CC me in tickets that are for Osama. I'm organising his board and if i'm not aware of the task, it risks not happening because it's not planned in a sprint. Once we have a better process established, this step could be skipped, but for now that's the best way to ensure that stuff will get done.

I'm assuming there is no need for visuals here and the next step is that page you describe in the previous comment @jawache ?

**Comment by jawache** [comment]
@zanete no need to create new visuals, can reuse the same ones from the existing sogs site. Time is important here so whatever we can get done in a few hours is fine.

**Comment by jawache** [comment]
@osamajandali could you get something quick together by EOD tomorrow (Wed) it doesn't have to be great but we've only got a few weeks to push the survey so need something here ASAP.

**Comment by holanita** [comment]
@osamajandali how is this going? let us know if this is blocked or there are any other issues. cc @zanete

**Comment by osamajandali** [comment]
I am working on this and hopefully will be ready by today.

**Comment by holanita** [comment]
@osamajandali thanks just one comment from my end to adjust the copy a bit:
Replace this: _Sign up below if want access when it's released_
With this: _Sign up below if you want to receive our report when it's released_

**Comment by osamajandali** [comment]
@holanita Done

**Comment by holanita** [comment]
@osamajandali perfect thanks. I've set up the redirect in Survey Monkey so I'm closing this ticket.
