### ISSUE TITLE
Replace top banner on website

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#58]
Why: the Hackathon is over and we have to promote SOGS from now on
What: replace the Hackathon banner with a new one that Jenya just created for SOGS
When: ASAP

Hello @osamajandali please replace the banner as explained above. Here is the new file to use, it's named as V2_final:
https://drive.google.com/drive/folders/1t-Ow-EdnpYyZwPuOMXwDSAUp8BAf2cyw

**Comment by holanita** [comment]
Sorry forgot to add. As [suggested](https://github.com/Green-Software-Foundation/state-of-green-software/issues/44), by @NAMRATA-WOKE, please use this url: grnsft.org/sogs/survey

**Comment by osamajandali** [comment]
Done!

**Comment by holanita** [comment]
@osamajandali thanks. The banner looks a little different from the image we have in the above folder. [This is the direct link ](https://drive.google.com/file/d/1_AfUD7QR89FIxoHYVH05t0vq1vcNN8Yk/view?usp=share_link)to the png. Both the text and placement are a bit different on the website now. Can you match Jenya's png?

<img width="1440" alt="Screenshot 2022-11-17 at 11 39 14" src="https://user-images.githubusercontent.com/100846607/202424776-afb9e96f-9ed8-4631-807f-d650598f1b83.png">

**Comment by zanete** [comment]
@holanita is this a duplicate of https://github.com/Green-Software-Foundation/ops-admin/issues/83 ?

**Comment by holanita** [comment]
@zanete could be. I'm sorry, I won't have capacity to keep an eye on your cops tickets. I'm executing the tasks that I am given for marketing, but I can't check for duplicates :(

**Comment by zanete** [comment]
@holanita is it that someone tells both of us what needs to happen and we both try to action at the same time? :D

**Comment by holanita** [comment]
@zanete we talked about this with Asim and Namrata when we put together the marketing calendar at the beginning. it sounded like an actionable item, I wasn't aware that it was in progress already. I've asked Asim about this today and he says it was just a one-off thing and there should be no other overlaps.

**Comment by zanete** [comment]
yeah, no worries, i agree it's probably down to the fact that the COP Announcements project had to exist, so I had to stick my fingers into everything. but going forward that shouldn't be the case.
