### ISSUE TITLE
Incorporate the Podcast into our marketing plans

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#60]
Hey @NAMRATA-WOKE so in [our marketing calendar](https://docs.google.com/spreadsheets/d/1DkXXU9SLX4Wfsd1lf1c4oC0_3ZVsuSSiy9PYABMLAMI/edit#gid=541890420) we had the podcast scheduled for November 11, but in the end Episode 10 was published on November 10. Just wanted to make sure you are in touch with Chris and you are incorporating the podcast into your marketing activities/posts?

**Comment by holanita** [comment]
I'm not sure if this has been discussed while I was off @NAMRATA-WOKE? I don't know much about the podcast, but I just found [this update from Zanete](https://github.com/Green-Software-Foundation/ops-admin/issues/11#issuecomment-1324332930) in my inbox after my return. might be useful.

**Comment by holanita** [comment]
Here is a new one from Asim: https://github.com/Green-Software-Foundation/ops-admin/issues/84#

**Comment by NAMRATA-WOKE** [comment]
@holanita 
I am not socializing the podcast. I believe that's being handled by the podcast team - not sure who all is involved in marketing the podcast at the moment. So, I cannot influence the URLs and copy they use!

**Comment by holanita** [comment]
ok noted. I wasn't aware that there is someone else posting on social media not just you. I suggest we discuss this in our next call with @jawache to avoid duplicating or missing anything just like it happened with the website banner recently.

**Comment by holanita** [comment]
I'm closing this task. Asim confirmed today that Chris is taking care of this.
