### ISSUE TITLE
Promote SOGS to software dev group on Linkedin

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#61]
Hey @NAMRATA-WOKE so we have this task in our marketing calendar about promoting the survey to a software dev group on Linkedin. This hasn't been updated for a while so I was wondering if this is done or is still to do? See here:
https://docs.google.com/spreadsheets/d/1DkXXU9SLX4Wfsd1lf1c4oC0_3ZVsuSSiy9PYABMLAMI/edit?disco=AAAAjnbKt4w

**Comment by NAMRATA-WOKE** [comment]
Yes mark it as done.
