### ISSUE TITLE
Alternative survey for the C Suite

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#63]
_Nov 28: on hold and to be reconsidered next year as per Elise's request. Discussed this with Namrata briefly yesterday and she suggested to use the word contributing partners instead of sponsors as there are no monetary considerations._

Next steps as discussed with Asim on Wednesday:

- [x] Sean to confirm any requirements we might not be aware of
- [x] Waiting for Juliette/Niels to share their one paragraph summary asap
- [x] Anita to draft document on possible [touch points](https://docs.google.com/document/d/1jJ9or3EpZ6zLZTtWzFGaj2FlirusHh8GAsrMJuH52pM/edit#).
- [ ] Ismael, Tamara to add their ideas asynchronously 
- [x] Asim to discuss with Elise on Nov 28 (Chris Adas could not attend the WG call)
- [ ] Reach out to SC via email by end of next week
- [ ] Can go ahead in early December unless any objections from the SC

**Comment by holanita** [comment]
@jawache did you have the chance to discuss this with Sean? I'm waiting for Juliette/Niels and Tamara/Ismael. Will be off next Monday and Tuesday so trying to follow up as much as possible, but please keep your eyes on this early next week if you can.

**Comment by jawache** [comment]
@holanita He agreed we need to raise with SC and offer them the same terms/opportunity.

**Comment by jawache** [comment]
I've instead started raising with individuals from the SC, seeing what they say - if there is a strong negative vibe then we'll know soon. Starting to suspect there will be, not sure how to sell it in a way that works for everyone 🤷‍♂️

**Comment by holanita** [comment]
Follow up on Dec 1 / waiting for feedback from Elise

**Comment by holanita** [comment]
TBD in the WG call today.

**Comment by holanita** [comment]
Elise asked that we reconsider this for next year. @jawache will you email BCG to let them know?

**Comment by holanita** [comment]
All done. This has been added to our future plans. 
- https://github.com/Green-Software-Foundation/state-of-green-software/issues/70
