### ISSUE TITLE
Discuss new layout and process for newsletters

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#64]
@jawache this isn't just related to the SOGS project, but I've tried so many things and this time I'm hoping that if I put this in the SOGS marketing agenda, this will work :) 

I think we need more clarity on how you envision
- the new **layout** of the newsletter (you sent us 2 examples via email)
- the new **process** of creating content for the newsletter (who does what)

To be discussed 
- If and how **Urs and / or Namrata** should be involved. 
- Who can take care of **Mailchimp** now? Namrata has no access.
- Will **Steph** still be involved?

If you want to continue doing the newsletter, then we are fine as we are. But if you want someone else to do this for you, it would be nice to either give them a written brief or have a call where you delegate this task and explain your expectations.

**Comment by jawache** [comment]
I agree (I actually created that newsletter and format when I was at ClimateAction.tech ;) ) There was a ton of resistance from the people but now people talk about it as one of the best features of CAT!

The trick is getting enough information to put in there weekly without it requiring a huge effort. The only way this is going to work is if the process becomes effectively brainless. My suggestions are:

- Subscribe to the CAT newsletter (and several others) and re-post the relevant links from there in ours.
- We have a weekly podcast, post that, post old episodes if there isn't a new one.
- There is at least one other green software podcast. https://greenio.gaelduez.com/
- Things posted on our # news channel on Slack.
- Things we have been tagged with in Socials.
- Create a google alert for "Green Software Foundation", "Sustainable Software", "Green Software" and share relevant things posted there.
- Watch Party - A video of a green software talk at a conference.
- Add a google form to the bottom of every newsletter asking for things to post.

Super simple, basic formatting.

First thing in the newsletter should be the main thing we want to bring peoples attention to, so for the next month or two it's just the SoGS survey.

@NAMRATA-WOKE if you have time can you take this on and create the copy/doc for this weeks newsletter? We can go our Friday like you suggest so we have time.

**Comment by NAMRATA-WOKE** [comment]
Sure I'll put something together for this Friday. Another "section" I recommend adding is "Green Software Gigs". Consolidating career opportunities in a newsletter and on social is a big crowd puller!

**Comment by NAMRATA-WOKE** [comment]
@jawache will you create the google form that will go at the bottom of every newsletter asking for things to post? Let me know if you want me to do that. Also, who will be scanning responses?

**Comment by holanita** [comment]
@NAMRATA-WOKE fyi [this](https://docs.google.com/forms/d/19W4MffxDd6KNAqfuryQwzJnIz7KvXvAfn5R37pxqXKk/edit) is the form we've been using so far. feel free to create a new one if you have to. also, if you are the one who puts together the content, it might be best that you scan responses too. I guess you can turn to Asim if you are unsure about something, but the more you can do without him the better / faster.

**Comment by holanita** [comment]
@NAMRATA-WOKE hi. just wanted to follow up to make sure this is on track to be sent out tomorrow. let me know if you need any help.

**Comment by NAMRATA-WOKE** [comment]
I don't have access to send out the newsletter. Waiting on @jawache to approve content and structure.

**Comment by holanita** [comment]
@NAMRATA-WOKE I see. Where is your draft saved? I can't see anything in Mailchimp nor [in our shared folder](https://drive.google.com/drive/folders/1cAqD--DS4WsYwC7HJZSRBugUnO3-VxT6).

**Comment by NAMRATA-WOKE** [comment]
Here is the doc to the newsletter: https://docs.google.com/document/d/17Hwj3nIO7swdpjYesDqlGIpFsBdIrx3JIv94JiJgSho/edit

**Comment by holanita** [comment]
@NAMRATA-WOKE ok. can you move this to [our shared folder](https://drive.google.com/drive/folders/1cAqD--DS4WsYwC7HJZSRBugUnO3-VxT6)? I'll let @jawache know that you are waiting for his approval. I think he wasn't aware. please use our shared folders and keep the github tickets updated so we can keep track of our progress.

**Comment by NAMRATA-WOKE** [comment]
@jawache not sure you got the notifications yesterday re: reimagined newsletter. Here it is: https://docs.google.com/document/d/17Hwj3nIO7swdpjYesDqlGIpFsBdIrx3JIv94JiJgSho/edit?usp=sharing

I also tagged @seanmcilroy29 for content in case he has updates from the WG that we can include. 

Let me know what you think. 

cc. @holanita

**Comment by jawache** [comment]
Thanks @NAMRATA-WOKE it's a good start, I don't think this is going to be the final format In the interest of making sure we have a weekly newsletter let's send this one out as it is on Friday. 

As a requirement for this newsletter I want a process that takes max 1hr from 1 person a week and that anyone can take over any week without confusion. I'd like a newsletter process designed around these constraints. 

Currently the content is good but feels very subjective, it's unclear to me why one article appears in one section and not the other. Let's have very objective obvious headings so anyone can do the newsletter without having to engage their brains too much.

The very top should be one image and one call to action - this is the main thing we want them to click on every week.

Next let's have some more obvious headings:

= Announcements

- Anything we specifically want to announce other than the main CTA. E.g. articles from our blog, new members joining etc... 

= Minutes

- List of all our meeting minutes so people can see what we are up to. We can find all the minutes from last weeks meetings using this link: https://www.google.com/url?q=https://github.com/issues?q%3Dlabel%253Ameeting%2Bis%253Aclosed%2Buser%253AGreen-Software-Foundation%2B&sa=D&source=docs&ust=1669329695491356&usg=AOvVaw090MfUut03J9KRD9gwlwT7 

So e.g. from the list above this is the meeting this week for the principles project (the training project) https://github.com/Green-Software-Foundation/training/issues/124

= Podcast

- Our and other podcasts (remember Green IO is another green software podcast)

= News

- News articles from around the internet, events.

= Jobs

= Explore

You had a few links to our projects like submitting a Call For Papers, link to the SCI etc.. these are things that will be around every single week. I don't think we should mention them every single week in the higher up parts of the newsletter so perhaps just put them at the bottom here, like Tier 2 call to actions.

**Comment by jawache** [comment]
Something else that's interesting (and I like) is that Hyperledger use this process to plan their weekly newsletters: https://wiki.hyperledger.org/pages/viewpage.action?pageId=78021660

We could do the same with issues.

- Use GH issues to flesh out the content of the newsletter.
- Each GH issue is for a specific weeks newsletter, the issue already has the headings, we flesh out the content during the week and then post on Friday.
- On Monday create a GH issue for this weeks newsletter.
- In our Monday call we dedicate 5 mins to the newsletter, decide quickly the main CTA and the other PMs have a moment to add/highlight anything.
- The PMs share the Newsletter GH issue in every WG and Project meeting during the week, members can comment on the GH issue if they would like us to add something in the newsletter.
- Thu evening you take the content of that issue and schedule the newsletter to go our Friday.

**Comment by holanita** [comment]
Sounds good to me @jawache I had [a GH issue](https://github.com/Green-Software-Foundation/ops-content/issues/12) for the newsletter that was due on Nov 15. I'll create something similar for next week's issue. The issues will live in the content repo and any PM can add them to their own repo if they want to.

**Comment by holanita** [comment]
So I've created the above issues for the latest newsletters. Let me know if you agree with the content of [this ticket](https://github.com/Green-Software-Foundation/ops-content/issues/15).

**Comment by holanita** [comment]
I'm closing this. We'll clarify the last steps here on the fly:
- https://github.com/Green-Software-Foundation/ops-content/issues/15
