### ISSUE TITLE
Create marketing package for members

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#66]
Who: Namrata
When: early next week as discussed previously with Asim
What: send a follow-up email to our members 

Details:
- send a follow-up email to all the members who had been contacted by Asim already and attach the [package for members](https://docs.google.com/document/d/1BZk16PONxDKKl4vN2w2qJP72pncV1v0Pe06z-vQC4yw/edit#heading=h.439blf1uqmxe)
- make sure you reply back to the emails Asim had sent on Nov 10 just before COP (you were in cc)
- make it clear that their internal team (colleagues) should be using the custom url that Asim had shared earlier
- plus, if they can promote this in their external channels as well, we have a new link for them that they can find in the new package

@NAMRATA-WOKE I have just confirmed the above with Asim. I'm creating this new ticket so we separate this from [partners](https://github.com/Green-Software-Foundation/state-of-green-software/issues/43).

**Comment by NAMRATA-WOKE** [comment]
https://docs.google.com/document/d/1q88-cp_qrR7GangLJhUWDvP-JbcvhI45Rs4Cv9ka1Ec/edit?usp=sharing

@holanita please share the collector link for partners. I'll create the appropriate short link. This document is for partners, not including CNCF and Hyperledger because they will also get a custom URL. For them, they'll receive a separate one more like the members. Please confirm: will GSF offer CNCF and Hyperledger reports if they reach a certain volume of responses?

**Comment by holanita** [comment]
@NAMRATA-WOKE sorry I added notes to the wrong ticket last time. So 
- I've reached out to most companies that assigned to myself. Let's see.
- How is it going with yours? Did you get any feedback?
- I think you can send out that general email to all other companies as I don't have any direct contact with anyone else on the list. 
Let me know how it goes.

**Comment by holanita** [comment]
Also, the convos about the collector above are on the wrong ticket. Let me transfer them to the one about partners.

**Comment by NAMRATA-WOKE** [comment]
Haven't received any feedback as yet. Reached out to all the rows that now have a checkmark in column M: https://docs.google.com/spreadsheets/d/1x_R9Z0qIn7WGvSA_tuW2QHiJIOBjlR0OhjzuLg6aFFk/edit#gid=95243021

**Comment by holanita** [comment]
OK, let's wait a bit longer and see what else we can do on the other tickets.

**Comment by holanita** [comment]
@NAMRATA-WOKE this ticket has become a bit too long and difficult to track. Let me create a new ticket for tracking our activities and conversions.
