### ISSUE TITLE
Map of the Green Software Ecosystem

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#68]
@Leamsi9 as requested by Asim – For the map sections, grab some screenshots of other "maps" so we can get on the same page on what you are thinking of for this section and so Osama has some ideas for how to design this.

**Comment by Leamsi9** [comment]
This is done, in the Maps section 3 of https://docs.google.com/document/d/1AhkCZWPcdFJBV_nk27xhip-2aiW-RBmb/

**Comment by holanita** [comment]
@jawache please see above and let us know your thoughts either here or in the document

**Comment by holanita** [comment]
**Important note from Asim to keep in mind:** make sure we are just focusing on the players that have the same focus on green software as we do (i.e. making software more sustainable not using software that makes the world more sustainable). The list should not be too broad. It will be used by the Policy WG to craft its roadmap. Let's get an initial list together and review them with the PolicyWG before it grows too much. @Leamsi9 was thinking of doing this after the TOC sections.

**Comment by holanita** [comment]
Closing these individual tickets. To be summarized and continued in a new issue:

Stakeholder map:
- This is done, in the Maps section 3 of https://docs.google.com/document/d/1AhkCZWPcdFJBV_nk27xhip-2aiW-RBmb/
- Note: make sure we are just focusing on the players that have the same focus on green software as we do (i.e. making software more sustainable not using software that makes the world more sustainable). The list should not be too broad. It will be used by the Policy WG to craft its roadmap. Initial list has been reviewed by the PolicyWG. Chris requested we group stakeholders. Cameron can now proceed accordingly.
