### ISSUE TITLE
Tasks for Ismael for December

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#69]
As discussed with Asim recently, we might start doing weekly sprints with Ismael to make things easier. A call has been scheduled with Ismael for tomorrow. Topics that we will potentially discuss:

1. asap: input for Osama (just lorem ipsum) so he can start working on at least one TOC section
2. asap: interviews - we need the draft questionnaire, Asim will interview the SC, does Ismael have any capacity?
3. asap: add the [business case](https://docs.google.com/document/d/1cgy-38nOnW3L98d7mr4OnInHVxKpR2zd/edit) to Ismael's [report outline document](https://docs.google.com/document/d/1ahV9DCoS16rIJXF1c4-6wYf9sNcIXUxrFEfibW4Q54c/edit) so we have everything in one place
4. asap: add screenshots of the 'sample maps' to Ismael's [report outline document](https://docs.google.com/document/d/1ahV9DCoS16rIJXF1c4-6wYf9sNcIXUxrFEfibW4Q54c/edit)
5. tasks that others can work on (Tamara offered help with the desk research & interviews, how about Doha?)

**Comment by Leamsi9** [comment]
All 5 of these tasks completed today, and updated in corresponding tickets.

**Comment by Leamsi9** [comment]
4. unblocked for the interviews Stephanie is booking.

**Comment by Leamsi9** [comment]
4. Is complete
5. Happy to collaborate with Tamara on desk research and interviews, likewise with Stephanie and maybe Doha on setting up interviews. There is also design work, particularly around charts and graphs, and we discussed at the start the possibility of copy editing by Urs.

**Comment by holanita** [comment]
@Leamsi9 
- noted on the new document. I've added watermarks to the old one so we don't use that for sure
- I've asked Asim to review your draft questionnaire. when are you planning to do the interviews? what's your avail?
- also asked Asim to review the sample maps (pls don't forget to tag him next time you send something for his review)
I'm going to schedule in our first weekly for tomorrow. Just 15 minutes before you leave...

**Comment by Leamsi9** [comment]
Re: interviews availability from Dec 8, UTC -6, as per my calendar. Communicated to @Stephaniestocker

**Comment by holanita** [comment]
to be continued in the weekly sprints from now on:
- https://github.com/Green-Software-Foundation/state-of-green-software/issues/71
