### ISSUE TITLE
Help Build the Stakeholder Map of the Green Software Ecosystem

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#73]
**We are collecting here all the organizations in the green software ecosystem that we should be paying attention to.** 
We are focusing on the players that have the same focus on green software as we do (i.e. making software more sustainable not using software that makes the world more sustainable).

The input will be used for our [State of Green Software Report](https://stateof.greensoftware.foundation/). 
Anyone is open to contribute and add suggestions to this list.
We are expecting suggestions by the end of this week i.e. December 9 COB.

**Comment by holanita** [comment]
Examples: sustainableit.org

**Comment by erikdtw** [comment]
https://www.cloudcarbonfootprint.org/

**Comment by holanita** [comment]
Note: all the suggestions shared so far have been incorporated into our draft document. Thank you!
