### ISSUE TITLE
Send marketing package to partners

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#75]
What: send our marketing package to partners as a PDF attachment
When: asap as the year-end holidays are approaching and we should promote the survey as much as possible
Statues: to be tracked here below

- [x] CNCF ([custom package](https://docs.google.com/document/d/1Cv5OcTUpAgmpwCOXozCpPgY-TbBxmxA8b5jBYjAaECM/edit#))
- [ ] Hyperledger ([custom package](https://docs.google.com/document/d/1ooXUg_fDgAZgeFuIT39I4DM5DrNjB4zjoPj6V6qW6jo/edit#))
- [ ] FinOps ([general package](https://docs.google.com/document/d/1q88-cp_qrR7GangLJhUWDvP-JbcvhI45Rs4Cv9ka1Ec/edit#heading=h.439blf1uqmxe) to be used for all partners except for CNCF and Hyperledger)
- [ ] .Net Foundation
- [ ] Python Software Foundation
- [x] Microsoft (Green Community)
- [x] Amazon
- [ ] IBM
- [x] Salesforce
- [x] Google
- [x] Green Web Foundation
- [x] Software Sustainability Institute
- [x] DEV Community
- [x] BFD community
- [x] Ismael to repost on behalf of Adora Foundation.
- [ ] Can also reach out to Founder world to see if they can send a note about the survey to their Developer Network meetup (7,582 members): https://www.meetup.com/developer-network/

**Comment by holanita** [comment]
@NAMRATA-WOKE which partners have you already shared the package with? Please update the above checklist to reflect the status as of today. Please reach out to everyone. Let's also clarify what packages we have. See the list above.

**Comment by holanita** [comment]
@NAMRATA-WOKE I've added to the list the ones that you had contacted before as per [this convo](https://github.com/Green-Software-Foundation/state-of-green-software/issues/43#issuecomment-1337583338).
@jawache do you want to contact CNCF and the rest yourself? If not, pls give us the names and email addresses.

**Comment by jawache** [comment]
I'll contact the rest myself thanks

**Comment by holanita** [comment]
@jawache can we consider this done or are you still working on reaching out to a few more partners?

**Comment by jawache** [comment]
@holanita I've received zero response from the list I've tried so let's close this one out, we tried.

**Comment by holanita** [comment]
I don't see any conversion or even clicks so this was probably not worth the effort indeed.
