### ISSUE TITLE
Create banner on the SDK repo

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#76]
@NAMRATA-WOKE as discussed [on Slack](https://greensoftwarefdn.slack.com/archives/C0477KHR7LK/p1670244349876739), please create a banner that can be placed [here](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/README.md). Let me know when you are done and then me or Osama will add that banner to the repo.

**Comment by NAMRATA-WOKE** [comment]
![AD banner_650 × 350 px](https://user-images.githubusercontent.com/114516498/206735794-3a1b88f8-ca41-48fe-bb28-7118d6d8fd6c.png)
 @holanita

**Comment by holanita** [comment]
@NAMRATA-WOKE shouldn't the image be much narrower (meaning height should be reduced) to fit? We could ask Jenya to help create something that has the exact parameters we need.

**Comment by holanita** [comment]
Let's continue here, asked Jenya to tweak the image: https://github.com/Green-Software-Foundation/state-of-green-software/issues/79
