### ISSUE TITLE
Create banner for the SDK repo

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#79]
Hey @Jenya-design could you help us create a SOGS banner that can be used [on this page in the SDK repo](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/README.md). We are about to remove the Hackathon one and need a SOGS one to replace it. [This](https://user-images.githubusercontent.com/114516498/206735794-3a1b88f8-ca41-48fe-bb28-7118d6d8fd6c.png) is an example @NAMRATA-WOKE has created – we could use something like this, just need this to have the same format as the image that we now have in the SDK repo. Let me know if you need further info.

**Comment by Jenya-design** [comment]
Sure @holanita will do in camva

**Comment by Jenya-design** [comment]
@holanita @NAMRATA-WOKE 

Please check the update here (3 options)
https://www.canva.com/design/DAFUjOAceZQ/CCbBKJAYdL4zX7EoEJqUiA/edit?utm_content=DAFUjOAceZQ&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

It's saved to the canva folder with other SoGS designs
https://www.canva.com/folder/FAFSM-YIxj4

Let me know if you need any adjustments

**Comment by zanete** [comment]
> @zanete how do I add this to the design discipline board? I don't have it in the dropdown anymore.

@holanita that is strange, I will add you to all the discipline projects and let's see if that makes it appear.
Just out of curiosity, do you see all three tabs when clicking on the projects cog? 
![Screen Shot 2022-12-12 at 12 22 17 PM](https://user-images.githubusercontent.com/35653799/207044050-763fde64-7d2d-43a6-bd6c-36aec124b67e.png)

**Comment by holanita** [comment]
Yes, I saw all 3 tabs, but I didn't see graphic design in the dropdown
<img width="340" alt="Screenshot 2022-12-12 at 11 28 12" src="https://user-images.githubusercontent.com/100846607/207044438-5818e094-b071-4358-84b4-dc0b71d83b1c.png">

**Comment by holanita** [comment]
Do I have to switch to org? I can see it when I choose that tab, but I've always used the recent tab and it worked so far... 

@Jenya-design the images look fab btw. I'll see if I can upload it to the SDK repo. Thanks! :)

**Comment by zanete** [comment]
@holanita yes, the recent one only contains ones that you have recently used, so as soon as you used the graphic design once it will be in your recent, too

**Comment by holanita** [comment]
@zanete interesting, I'm pretty sure graphic design is one that I used recently. I've never used the marketing one and I still see it. Anyways, this ticket looks good now, so all good :)

**Comment by holanita** [comment]
Closing this. Opened a PR in the SDK repo. Will be following up with Vaughan separately.
