### ISSUE TITLE
2023 01 04 - Overview - Desk research and insights (draft)

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#85]
Master file(s) that contain the whole desk research:
- [This](https://docs.google.com/document/d/1AhkCZWPcdFJBV_nk27xhip-2aiW-RBmb/edit) is the latest document that now contains the business case (see in section 2).
- [This](https://docs.google.com/document/d/1ahV9DCoS16rIJXF1c4-6wYf9sNcIXUxrFEfibW4Q54c) is a new, equivalent doc containing the whole report. Unsure if this is still relevant, Ismael mentioned this when discussing knowledge.

Business case:
- Supposed to be a summary. No urgency from a design perspective, can be the last one to complete. See link above.

Knowledge:
- [Latest version – Insights](https://docs.google.com/document/d/19fsrUutANbB4J9PLfcFLOrMpw9wTugxjtMXARFyWL8Q/edit?usp=drivesdk) - 10 seem to be fairly complete, not approved yet

Culture:
- [Latest version – Insights](https://docs.google.com/document/d/1vVlxQvASWr_a4P8vJxM5mATLYIiRCdzuN0y1GUvN3Aw/edit#) - 5 seem to be fairly complete, not approved yet
- we could benefit from more thought on tagging
- get Namrata's opinion on titles as we get closer to naming the insights (should be impactful, viral, sharable)

Tooling:
- missing

Stakeholder map:
- This is done, see the Maps in section 3 of the first document referenced above.
- Cameron will continue working on this in line with the feedback we received from Chris re: grouping.
- Note: focus on the players that have the same focus on green software as we do (i.e. making software more sustainable not using software that makes the world more sustainable). The list should not be too broad. It will be used by the Policy WG to craft its roadmap. Initial list has been reviewed by the PolicyWG.

**Comment by holanita** [comment]
@Leamsi9 @jawache fyi this is a summary of where we are right now and what documents you've been working on so far.

**Comment by holanita** [comment]
Also, just a reminder that we had two checklists we wanted to keep in mind: [PR FAQ Checklist](https://github.com/Green-Software-Foundation/state-of-green-software/issues/29) and [Content & Marketing](https://github.com/Green-Software-Foundation/state-of-green-software/issues/28).

**Comment by jawache** [comment]
Thanks for adding this clarity @holanita
