### ISSUE TITLE
Update the SOGS website

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#86]
Why: we are no longer asking people to complete the survey
What: update the content at https://stateof.greensoftware.foundation/

Hi @osamajandali I'd recommend we backup the current content so we can easily re-use it when we run the survey again.

And for the time being, let's just remove from the main page everything related to completing the survey.
- In the top section, remove _Get involved, take the 5 min survey now_ + button
- Remove the _Survey Details_ section 
- Remove the _Do you want to help make a difference_ section including button
- Remove the _Take the survey now button_ underneath taking climate action

**Comment by holanita** [comment]
@NAMRATA-WOKE since you want to use this page for pre-report promo, please double check if the edits I suggested above are fine. by when do you need the page to be udpated?

**Comment by osamajandali** [comment]
@holanita thank you.. will check them out very soon

**Comment by NAMRATA-WOKE** [comment]
@holanita not starting pre-promotion until week 1 in February!

**Comment by NAMRATA-WOKE** [comment]
The only comments I have for now include:

Keep a CTA button above the fold, but change to: "Send me the report" 

Instead of removing button under "taking climate action" section, change it to: View Current Projects to link back to GSF site: https://greensoftware.foundation/projects/ and to help drive traffic and interest in existing initiatives and communications. 

Once people click one of the CTA buttons and provide their email address and click the final "send me the report" button, if they can be prompted to share they've done so on social media in a post tagging GSF, that would be great. LinkedIn is preferred.

**Comment by zanete** [comment]
@holanita are you happy for @osamajandali to start on this or we still need more info and details?

**Comment by osamajandali** [comment]
All done!
Except for that one for sharing social media links that @NAMRATA-WOKE mentioned. I would like to know the exact behavior you have in mind, in detail, if you can.

**Comment by holanita** [comment]
Thanks @osamajandali! 
@NAMRATA-WOKE pls let Osama know about the social stuff.
(Also Namrata let's not promote the projects page anywhere else for now. It is out of date and needs a lot of update.)

**Comment by zanete** [comment]
just to clarify @NAMRATA-WOKE , what is needed here is
- The copy that should be shown after people subscribe to get the report
- what social platforms (LinkedIn, Twitter etc) should be added
- If there should be any pre-populated copy when they click to share or is it just the link of this SOGS website

**Comment by NAMRATA-WOKE** [comment]
COPY AFTER PEOPLE SUBSCRIBE PRE-LAUNCH (TWITTER/LINKEDIN): 

Green Software Foundation is about to publish the first ever State of Green Software Report. I'm on the list to receive it. Are you? Subscribe today! #SOGS2022 #greensoftware 

COPY AFTER PEOPLE SUBSCRIBE POST-LAUNCH (TWITTER/LINKEDIN): 

Join me in learning about the latest trends, challenges and opportunities to achieve advancements in green software development and wide-scale industry adoption. Download the State of Green Software Report now! #SOGS2022 #greensoftware 

@osamajandali

**Comment by osamajandali** [comment]
@NAMRATA-WOKE Thank you for providing the copy.
One last thing, what should the message say after the people submit the form?  Besides saying thank you for submitting, there should be something like" Spread the word by sharing on Twitter and Linkedin."

**Comment by NAMRATA-WOKE** [comment]
@osamajandali can you clarify where this message will appear?

**Comment by osamajandali** [comment]
@NAMRATA-WOKE didn't you mention that above? from what I understood that there should be some sort of sharing buttons after people submit the form
here:
![Screenshot 2023-01-25 at 4 17 05 PM](https://user-images.githubusercontent.com/13832392/214587559-d4d45d12-8f0e-47f1-aade-a49073a11df2.png)

**Comment by osamajandali** [comment]
@NAMRATA-WOKE how about having the search button underneath it? and I think it is better to keep the old confirmation copy.

I was asking for what it should say if I want to put it underneath it.
I suggest 
Share: [Twiiter Icon]  [Linkedin Icon]

Will that work?

**Comment by NAMRATA-WOKE** [comment]
Ah, understood. That works @osamajandali

**Comment by NAMRATA-WOKE** [comment]
@osamajandali  Can you clarify what's not easy to do without a custom integration?

**Comment by osamajandali** [comment]
@NAMRATA-WOKE adding the share buttons

**Comment by zanete** [comment]
To summarise, it is not possible (unless we spend a lot of effort and time) to add the share buttons within the mailchimp form to appear upon submission. We can add the share buttons anywhere else in the website if needed.

**Comment by NAMRATA-WOKE** [comment]
@osamajandali how much time would it take and would it have a consequence on any other deliverables on your end? 

We could also entertain setting up a zap so that once an email is submitted and registered into a MailChimp audience, an automated email from Mailchimp is sent reminding folks to share the report with their network and climate friends!

**Comment by zanete** [comment]
@NAMRATA-WOKE @osamajandali 
cc @jawache @holanita 
Are we now suggesting that on registering an email address to recieve SOGS, the user should receive an automated email confirming that registration has been successful and that they should spread the word?
if so:
- [ ]  @osamajandali let us know if there an email sent currently? if so, what is the copy?
- [ ] @NAMRATA-WOKE What should the copy be?

FYI:
These are the automations i'm seeing in Mailchimp (but i'm not so familiar with this platform so I'm not sure if all are visible to me or these indeed are all that have been set up)
![Screen Shot 2023-02-09 at 1 25 09 PM](https://user-images.githubusercontent.com/35653799/217825103-c154e17d-bdae-4ba5-902e-d31ea96e8e8e.png)

**Comment by jawache** [comment]
I don't want any more effort spent on this version of the site, not worth it., going away in a month.

Dev effort should now go to the new version.

Marketing effort should be focused on the new version, as we get closer to the launch we should craft a plan.

I want a way we can control marketing effort and spend, not every project at every stage should have marketing effort spent on it. We have 2/3 big bets and I prefer all effort to go to them. Right  now it feels scattershot.
