### ISSUE TITLE
Finalizing Desktop Research

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/state-of-green-software#88]
I'd like us to finalize desktop research by end of today (11/01) and spend 12/01 and 13/01 just tying up loose ends (e.g. stakeholder map). 

We need to track everything in one place so please don't communicate these by email or slack and just reply to this ticket.

- [x] Add missing references to current insights.

By the end of today (11/01) please add any missing references to the knowledge, culture and tooling docs. Tooling especially is missing all references. Don't focus on adding any more insights at this stage, I'd like for us to complete any insights we've already drafted and by that I mean just make sure all the references are added and correct. Wordsmithing we can do after with the help of our editor.

- [x] Share current state of research for the stakeholder/ecosystem map

By the end of today (11/01) share current state of research for the stakeholder/ecosystem map, wherever you are, in whatever format it's in is fine, a CSV/Mind Map, anything is fine. Others are now getting involved with formulating this map and we need clarity about how to merge the two streams of effort.

We'll setup a call for us first thing tomorrow (your morning) to decide how best to use the final two days of your time on desktop research based on you responses to the above.

**Comment by Leamsi9** [comment]
Knowledge: https://docs.google.com/document/d/19fsrUutANbB4J9PLfcFLOrMpw9wTugxjtMXARFyWL8Q/edit?usp=sharing
Tooling: https://docs.google.com/document/d/1bluCWaOkWQNfH8aRyyTxcm22wJegFr6UmAU_YVXsox4/edit?usp=sharing
Culture: https://docs.google.com/document/d/1vVlxQvASWr_a4P8vJxM5mATLYIiRCdzuN0y1GUvN3Aw/edit?usp=sharing
Stakeholders list WIP: https://docs.google.com/spreadsheets/d/15yjRRAAi-TpW1gzJgslB38TsDOjwWgQ0/edit?usp=sharing&ouid=102759123097087113446&rtpof=true&sd=true
