### ISSUE TITLE
Insight 1: Digital does not equal green

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#95]
Parent issue #101 

**Insight lifecycle**

- [x] Draft is created (gdoc)
- [x] Reviewed by editor (gdoc)
- [x] Content reviewed by Marketing (gdoc)
- [x] Final approve by Tamara (gdoc)
- [x] Graphics created (gdoc -> assets)
- [ ] Published (gdoc -> md)

**Comment by NAMRATA-WOKE** [comment]
Insight 1 is done: https://docs.google.com/document/d/1TgBoISr8XwhoiikGQ_GeA32hLVxATL_ArMUKgfF9ums/edit# @Oleg-Zhymolokhov

**Comment by jawache** [comment]
Re: making images for each Insight. @Jenya-design

Each insight needs at least one main image, something that would look good when posted on social media etc... the image should have:
- The headline of the insight
- Mention this is the state of green software report 2023
- Some sort of link back to the website (stateof.greensoftware.org)
- Mention the Foundation.
- Anything else you think might be interesting/useful.

If the insight has some other graphics, like graphs and charts etc... those should also be updated to match the style of the Foundation.

All assets in the foundation are creative commons attribute - so specifically this license, https://creativecommons.org/licenses/by/4.0/ - it has some specific iconography we should align to.

**Comment by Jenya-design** [comment]
Hi @jawache 

Please let me know:
1. Those images are in the first place for social media posts or for articles also?
2. [This doc](https://docs.google.com/document/d/1TgBoISr8XwhoiikGQ_GeA32hLVxATL_ArMUKgfF9ums/edit#) contains all 6 insights and their names are approved?
3. I'm planning to use the same style as for the website (stateof.greensoftware.org), dark bg etc. 
Is it ok or you prefer those look like general GSF materials (annual report for example)
5. _If the insight has some other graphics, like graphs and charts etc... those should also be updated to match the style of the Foundation._ - is it possible to paste them in the doc (if they're related to the text)? So I can see the exact images you need redone.
6. Do you need the text editable in canva?
7. What's my deadline?
Thank you

cc @zanete @NAMRATA-WOKE

**Comment by Oleg-Zhymolokhov** [comment]
@Jenya-design please note, I've updated the title of Insight 1 in the document

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE  @Oleg-Zhymolokhov thank you for all the clarifications

Just to make sure I understand our process for this task correctly @Oleg-Zhymolokhov 
As soon as you have an insight ready for me, you'll create another issue, that I'll be able to see in my to do list here
https://github.com/orgs/Green-Software-Foundation/projects/9/views/1
Correct?

Thank you

**Comment by Jenya-design** [comment]
@Oleg-Zhymolokhov 
_I'd prefer to have all discussions related to a single insight under it's original issue. Creating another issue for every insight would be to much of a repetition._ 
- Ok, makes perfect sense it's just a part ' Each Insight issue is linked to the document...' confused me. I can see now that there's the whole tree of the existing issues already

_You can still see issues assigned to you, just in a different project._
- I understand, but it's much easier for me to track the tasks and your feedback when I can see them in Graphic Design project. 
I can create a separate issue in Graphic Design project, so we can keep all the 30-40 images and design-related discussion there.  You can tag me in the original insight issue or directly in the doc (as all the info I need is there anyway) when the Insight is ready. Does this option work for you?

I can proceed with the Insight 1? I can see there's a comment by Namrata
Thank you

**Comment by NAMRATA-WOKE** [comment]
@Jenya-design just add the graphic design project to the list of projects associated to the issue. That way it will appear on your board.

**Comment by Jenya-design** [comment]
Thank you @NAMRATA-WOKE my bad

**Comment by Oleg-Zhymolokhov** [comment]
@Jenya-design yes, you can proceed with Insight 1

**Comment by Jenya-design** [comment]
Hello @jawache @NAMRATA-WOKE @Oleg-Zhymolokhov 

Please check the update for the Insight 1 attached
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) here (curremntly 1-3)
Folder with the illustrations/elements also [here](https://www.canva.com/folder/FAFfC6DLAiU)

Currently the format is 1200x1200px for social media post, if the same images should be used for the website 
@osamajandali please let me know if you need any adjustments
Thank you

![Image](https://user-images.githubusercontent.com/69306070/229908046-377c536d-95f4-48c7-87c6-e89f23b63eae.png)

**Comment by jawache** [comment]
Thanks @Jenya-design.

- Are all the images going to be this dimension? These will be the cover images for each insight and will be displayed in multiple formats according to each social media platform, these will be embedded on the website on each insight page and thinking about it it probably makes some sense to put them on the insight page itself. @osamajandali can provide more guidance these will appear as the meta images for the insight pages so when you share the insight this is the default image that will appear on the share. For example it will appear like this when someone shares an insight URL on a social media site: https://www.linkedin.com/feed/update/urn:li:activity:7046884964063199232/

- No need to mention Report Q1 2023, there will only be one for 2023 - In fact you can just state "state of green software 2023 by the green software foundation" it can be pretty small the most important info is the insight itself.

- It's not immediately clear what the image is saying to me. It feels like we are just staying one thing "Digital != Green", it's not clear this text is just the title and there is a lot more information to back up this summary if you click the associated link and visit the webpage. It's basically a sharable quote from the website.

- Generally with the image we want people to understand (a) there is more detail about this insight on our website (b) this is an insight from a much bigger report and (c) there are lots more insights on the website.

- I'm wondering to make it clear that the insight is part of a collection maybe we could number then? So insight 1,2,3,4? Or maybe we could just state in the image 

Insight: "XXXXXX" 
from the 2023 state of green software report by gsf
pls visit stateof.greensoftware.org for more info

Last two lines above can be very small, the most important info is the insight itself.

**Comment by NAMRATA-WOKE** [comment]
@jawache  it's not the SOGS 23 it's SOGS 22, correct? I believe in previous promo we said SOGS 22. 

@Jenya-design couple of comments:
- the images need to incentize visitors to explore each insight so they have to be compelling and engaging.
- The main focus should be the insight, so we don't need to make the SOGS logo or name a big feature. 
- I haven't seen all of them yet but the visual can be stronger for Insight 1. Perhaps creating an illustration that conveys this point in the insight would be more powerful: Every digital transaction needs energy, physical infrastructure and a device to run.

Can share more later but that's my feedback for now! Hope it's helpful.

**Comment by jawache** [comment]
@NAMRATA-WOKE believe it should be 2023, we started in 2022 but will release in 2023 and the insights are valid for 2023.

**Comment by NAMRATA-WOKE** [comment]
Noted!

**Comment by osamajandali** [comment]
@Jenya-design awesome design! 
Just one note, same as @jawache said, the dimensions should be 1200x630px, and keep in mind not to put the text so close to the edges; just keep some padding for the text not to be cropped.

**Comment by Jenya-design** [comment]
Thank you all for your feedback, it was very helpful
Please check the update attached and let me know what you think, current size is 1200 x 630
I would like to approve this one before I move to the rest, so I can apply the same composition. 

@osamajandali to put the illustration on the insight page you need a full width illustration or rather an element like[ this one](https://stateof.greensoftware.foundation/images/hero-illustration.svg)? 
Like a hand with the phone in the current illustration for Insight 1.

@NAMRATA-WOKE @jawache it'll be 40 Insights in total and you'll need 1-2 images for each ready by May 15th. 
Do I understand this part correctly?

Thank you

![Insights SOGS_1200 × 630](https://user-images.githubusercontent.com/69306070/230121204-c00fe368-c6eb-4028-8fa4-0f245ec11a5a.png)

**Comment by jawache** [comment]
Thanks @Jenya-design I like how it's looking now. I'll let's @osamajandali weigh in on the padding etc...

- this isn't you but I realised that on mobile it looks like Digital = Green, so the exact opposite meaning than intended 😁 I'd suggest for this one and in maybe just "Digital does not equal green".

- I like the idea of using insight 1,2,3 but not sure how we'll end up numbering them , the current number is just almost random. @Oleg-Zhymolokhov / @tamigraph what do you think, just number them the order they are created or not number them at all?

- Note some of the future insights have a lot more text, something to take into account maybe.

**Comment by cathmaughan** [comment]
@Jenya-design I'd just make a couple of edits to the top 2 sentences.

- Make sure both sentences start with a capital letter (full stop at the end is not needed)
- For the second sentence, I'd rewrite slightly "Find out more at stateof.greensoftware.org"

I think, on @jawache 's point on whether to include "Insight N" as part of the title, I would remove as it takes up a lot of the header space and most of the title are much longer thatn this one. Also, if the insights are listed in a menu, the user may only be able to read the first part of the title. In which case, the "Insight" just gets in the way.

**Comment by Jenya-design** [comment]
Thank you @jawache 
Yes, I see considered that further insights will have at least two lines of the text

@cathmaughan thank you for the edits I left the ' From the 2023... Find out more at stateof.greensoftware.org' on top to make sure the main title won't be cropped on the various devices / platforms

**Comment by osamajandali** [comment]
@Jenya-design I used the image in the insight page [(Link)](https://heartfelt-babka-3b6ea9.netlify.app/insights/digital-not-equal-green/), and as you can see, we already have the title and logo in the page. so I think we need another version without logo, text, and title so I can use it inside the page and keep the current version for link sharing preview.
What do you think?

**Comment by Jenya-design** [comment]
Thank you @osamajandali  I agree, please check the attachment with the illustration only
If you need the smaller height, I can make it 500-510px

![01_Insights  SOGS_website elements-03](https://user-images.githubusercontent.com/69306070/230930101-7404c95c-0da0-4d63-b45a-209e78d2ef9e.png)

**Comment by NAMRATA-WOKE** [comment]
@Jenya-design looks good!
