### ISSUE TITLE
Insight 2: Software emissions as bad as air, rail, and shipping combined

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#96]
Parent issue https://github.com/Green-Software-Foundation/state-of-green-software/issues/101

**Insight lifecycle**

- [x] Draft is created (gdoc)
- [x] Reviewed by editor (gdoc)
- [x] Content reviewed by Marketing (gdoc)
- [x] Final approve by Tamara (gdoc)
- [x] Graphics created (gdoc -> assets)
- [x] Published (gdoc -> md)

**Comment by Oleg-Zhymolokhov** [comment]
@NAMRATA-WOKE Hey, I'm trying to sort out the assignees of the first 6 insights and it seems like they all should be assigned to Tamara, is this correct?

**Comment by Oleg-Zhymolokhov** [comment]
@Jenya-design this one is ready for you

**Comment by Jenya-design** [comment]
Hello @jawache @NAMRATA-WOKE @Oleg-Zhymolokhov

Please check the update for the Insight 2 attached and let me know if you have any comments
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) [here](https://www.canva.com/folder/FAFfC6DLAiU) (curremntly 1-3)
Folder with the illustrations/elements also here

Thank you

![Image](https://user-images.githubusercontent.com/69306070/229908640-783005b6-854f-4171-9d83-da0bc8c8bc3d.png)

**Comment by Jenya-design** [comment]
Hello @jawache @NAMRATA-WOKE @cathmaughan

Please review new update for the Insight 2 attached
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Folder with the illustrations/elements [here](https://www.canva.com/folder/FAFfC6DLAiU)


![Image](https://user-images.githubusercontent.com/69306070/231135770-75036281-d52f-41f8-b4b7-89c708af77ff.png)

**Comment by cathmaughan** [comment]
There is a slight accessibility issue in that not all screen readers will read the + and = symbols.
A suggested rewrite could be "Software emissions on a par with air, shipping, and rail combined" or "Software emissions  as bad as air, rail, and shipping combined"

**Comment by NAMRATA-WOKE** [comment]
@cathmaughan great feedback. In my view, the last rewrite works!

**Comment by Jenya-design** [comment]
Hello @jawache @NAMRATA-WOKE @cathmaughan

Please review new update for the Insight 2 attached
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Folder with the illustrations/elements [here](https://www.canva.com/folder/FAFfC6DLAiU)


![Image](https://user-images.githubusercontent.com/69306070/232443415-9b3c9fdb-7dc3-4470-ad2b-199f8c1724d7.png)

**Comment by cathmaughan** [comment]
For consistency, we should add the verb "Software emissions are as bad as air, rail, and shipping combined"

**Comment by Jenya-design** [comment]
Hello @NAMRATA-WOKE @cathmaughan

Image Insight 2 updated
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Folder with the illustrations/elements [here](https://www.canva.com/folder/FAFfC6DLAiU)

![Image](https://user-images.githubusercontent.com/69306070/233650350-b5b01669-8b9a-42f7-bd29-47555463b416.png)

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE @Oleg-Zhymolokhov 
Text is updated in canva according to the Namrata's request in[ Insights (All 30)](https://docs.google.com/document/d/147_VN3fAmIjlptURewQ6T4qMv8VJHRZc_UhoaHFy55A/edit) doc
png attached here

![Image](https://github.com/Green-Software-Foundation/state-of-green-software/assets/69306070/2b81bb35-f8b8-4124-98b9-bd2e2ac31896)
