### ISSUE TITLE
Insight 3: Green software is vital for a net zero future

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#97]
Parent issue https://github.com/Green-Software-Foundation/state-of-green-software/issues/101

**Insight lifecycle**

- [x] Draft is created (gdoc)
- [x] Reviewed by editor (gdoc)
- [x] Content reviewed by Marketing (gdoc)
- [x] Final approve by Tamara (gdoc)
- [x] Graphics created (gdoc -> assets)
- [x] Published (gdoc -> md)

**Comment by Jenya-design** [comment]
Hello @jawache @NAMRATA-WOKE @cathmaughan

Please review new update for the Insight 3 attached
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Folder with the illustrations/elements [here](https://www.canva.com/folder/FAFfC6DLAiU)


![Image](https://user-images.githubusercontent.com/69306070/231136028-de5d1671-94fb-4cf5-8c09-e30f22b1bccc.png)

**Comment by cathmaughan** [comment]
For the heading, 'software' shouldn't be capitalised. 
Wasn't there a discussion about this being SOGS 22, not 2023? Or is the survey 22 and the report 23?
Otherwise the copy looks good.

**Comment by NAMRATA-WOKE** [comment]
SOGS 23. @cathmaughan apologies if my edits reflected otherwise.

**Comment by cathmaughan** [comment]
Thanks for clarifying @NAMRATA-WOKE, that's my bad probably for misreading something

**Comment by Jenya-design** [comment]
Hello @jawache @NAMRATA-WOKE @cathmaughan

Please review new update for the Insight 3 attached
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Folder with the illustrations/elements [here](https://www.canva.com/folder/FAFfC6DLAiU)


![Image](https://user-images.githubusercontent.com/69306070/232444114-c3e6b263-ee06-40df-a284-3c7670e138ce.png)
