### ISSUE TITLE
Insight 4: Green software requires a holistic approach

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#98]
Parent issue https://github.com/Green-Software-Foundation/state-of-green-software/issues/101

**Insight lifecycle**

- [x] Draft is created (gdoc)
- [x] Reviewed by editor (gdoc)
- [x] Content reviewed by Marketing (gdoc)
- [x] Final approve by Tamara (gdoc)
- [x] Graphics created (gdoc -> assets)
- [x] Published (gdoc -> md)

**Comment by Jenya-design** [comment]
Hello @jawache @NAMRATA-WOKE @cathmaughan

Please review new update for the Insight 4 attached
Canva with [all the images for Insights](https://www.canva.com/design/DAFfKNR_CT0/Ygs85bhlUn7J0vOcc_4fOg/edit?utm_content=DAFfKNR_CT0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Folder with the illustrations/elements [here](https://www.canva.com/folder/FAFfC6DLAiU)


![Image](https://user-images.githubusercontent.com/69306070/232444285-74393e05-d216-4edd-853b-de5c07290e3b.png)
